import assert from 'node:assert/strict';
import fs from 'node:fs';
const base='http://localhost:8787';
const setupToken=fs.readFileSync('.dev.vars','utf8').match(/^ADMIN_SETUP_TOKEN=(.+)$/m)?.[1].trim();
if(!setupToken)throw new Error('Falta ADMIN_SETUP_TOKEN en .dev.vars para pruebas locales.');
const setup=await fetch(base+'/api/admin-auth/setup',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({email:'local-test@example.com',password:'Local-only-test-password-92!',token:setupToken})});
assert.ok([201,409].includes(setup.status),'Inicialización local');
let cookie=setup.headers.get('set-cookie')?.split(';')[0]||'';
async function request(path,{data,auth=true,method,origin=base,form}={}){const res=await fetch(base+path,{method:method||(data||form?'POST':'GET'),headers:{...(auth?{cookie}:{}),origin,...(data?{'content-type':'application/json'}:{})},body:form|| (data?JSON.stringify(data):undefined),redirect:'manual'});return res}
let res=await request('/api/shop',{auth:false});assert.equal(res.status,401);
res=await fetch(base+'/api/shop',{headers:{'oai-authenticated-user-id':'local_seedy','oai-authenticated-user-email':'fake@example.com'}});assert.equal(res.status,401);
res=await request('/administrador',{auth:false});assert.equal(res.status,307);assert.ok(res.headers.get('location').includes('/acceso'));
res=await request('/api/admin-auth/login',{auth:false,data:{email:'local-test@example.com',password:'incorrect'}});assert.equal(res.status,401);
res=await request('/api/admin-auth/login',{auth:false,origin:'https://untrusted.example',data:{email:'local-test@example.com',password:'Local-only-test-password-92!'}});assert.equal(res.status,403);
res=await request('/api/admin-auth/login',{auth:false,data:{email:'local-test@example.com',password:'Local-only-test-password-92!'}});assert.equal(res.status,200);const session=res.headers.get('set-cookie');assert.match(session,/Secure/);assert.match(session,/HttpOnly/);assert.match(session,/SameSite=Lax/);cookie=session.split(';')[0];
res=await request('/api/shop');assert.equal(res.status,200);const {shop}=await res.json();assert.ok(shop.id);
const form=new FormData();for(const [k,v] of Object.entries({name:'Producto de prueba local',description:'Prueba de fotografía',price:'100',shippingPrice:'120',department:'Ropa',category:'Camisas',availableMty:'1',availableCdmx:'1',options:'[]'}))form.append(k,v);form.append('image',new Blob([fs.readFileSync('public/samples/camisa.jpg')],{type:'image/jpeg'}),'camisa.jpg');
res=await request('/api/products',{form});assert.equal(res.status,200);const {product}=await res.json();assert.ok(product.image);
res=await request('/api/image/'+product.image,{auth:false});assert.equal(res.status,200);assert.match(res.headers.get('content-type'),/image\/jpeg/);
res=await request('/api/store/'+shop.id,{auth:false});assert.equal(res.status,200);assert.ok((await res.json()).products.some(p=>p.id===product.id));
const order={shopId:shop.id,customer:'Prueba local',phone:'528111111111',address:'Calle de prueba 123 Monterrey',fulfillment:'shipping',requestKey:crypto.randomUUID(),items:[{id:product.id,quantity:2,choices:{}}]};
res=await request('/api/orders',{auth:false,data:order});assert.equal(res.status,201);const {token:orderToken}=await res.json();assert.ok(orderToken);
res=await request('/api/orders',{auth:false,data:order});assert.equal(res.status,200);assert.equal((await res.json()).token,orderToken);
res=await request('/pedido/'+orderToken,{auth:false});assert.equal(res.status,200);const html=await res.text();assert.ok(html.includes('Prueba local'));assert.ok(html.includes('540'));assert.ok(html.includes('Enviar pedido por WhatsApp'));
res=await request('/api/admin-auth/invite',{data:{email:'invited@example.com'}});assert.equal(res.status,200);const {url}=await res.json();const invite=new URLSearchParams(new URL(url).hash.slice(1)).get('invite');
res=await request('/api/admin-auth/accept',{auth:false,data:{email:'wrong@example.com',password:'Test-invite-password-42!',token:invite}});assert.equal(res.status,403);
res=await request('/api/admin-auth/accept',{auth:false,data:{email:'invited@example.com',password:'Test-invite-password-42!',token:invite}});assert.equal(res.status,201);const inviteCookie=res.headers.get('set-cookie').split(';')[0];
const ownerCookie=cookie;cookie=inviteCookie;res=await request('/api/shop');assert.equal(res.status,200);assert.equal((await res.json()).shop.id,shop.id);
res=await request('/api/admin-auth/invite',{data:{email:'forbidden@example.com'}});assert.equal(res.status,403);
res=await request('/api/admin-auth/me');const invited=(await res.json()).user;cookie=ownerCookie;
res=await request('/api/admin-auth/revoke',{data:{id:invited.id}});assert.equal(res.status,200);cookie=inviteCookie;res=await request('/api/shop');assert.equal(res.status,401);cookie=ownerCookie;
res=await request('/api/admin-auth/logout',{data:{}});assert.equal(res.status,200);res=await request('/api/shop');assert.equal(res.status,401);
console.log('PASS: acceso privado, cabeceras falsas rechazadas, CSRF, cookies, foto JPG, catálogo, pedido con envío $300, reintento sin duplicado, resumen, invitaciones, permisos y cierre de sesión.');
