'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {ShoppingBag,Send,Link2,Printer,ArrowLeft,Check} from 'lucide-react';
import {money,fulfillmentLabel} from '@/app/shared';
import type {OrderSummary} from '@/app/order-types';
export default function Summary({order}:{order:OrderSummary}){
 const [url,setUrl]=useState(''),[copied,setCopied]=useState('');
 useEffect(()=>{setUrl(`${location.origin}/pedido/${order.token}`)},[order.token]);
 async function copy(){try{await navigator.clipboard.writeText(url);setCopied('Enlace copiado.')}catch{setCopied('Copia el enlace desde la barra de direcciones.')}}
 return <><header className="topbar"><div className="brand"><ShoppingBag/>{order.shop.name}</div><span className="order-payment">Pendiente de pago</span></header><main className="order-workspace"><div className="order-heading"><div><p className="eyebrow">{order.shop.id==='ejemplo'?'PEDIDO DE PRUEBA':'PEDIDO GUARDADO'}</p><h1>Resumen del pedido</h1><p>Folio {order.id.slice(0,8).toUpperCase()} · {new Date(order.date).toLocaleString('es-MX',{timeZone:'America/Monterrey',dateStyle:'medium',timeStyle:'short'})}</p></div><span className="order-saved"><Check size={18}/>Guardado</span></div><div className="order-layout"><div><section className="panel order-customer"><h2>Datos del cliente</h2><dl>{order.fulfillment&&<div className="wide"><dt>Forma de pedido</dt><dd>{fulfillmentLabel(order.fulfillment)}{order.fulfillment==='shipping'&&<small className="summary-shipping">El pedido sale de la sucursal Monterrey.</small>}</dd></div>}<div><dt>Nombre</dt><dd>{order.customer}</dd></div><div><dt>Teléfono</dt><dd>{order.phone}</dd></div><div className="wide"><dt>Dirección de entrega</dt><dd>{order.address}</dd></div>{order.notes&&<div className="wide"><dt>Notas del pedido</dt><dd>{order.notes}</dd></div>}</dl></section><section className="panel order-products"><div className="section-title spread"><h2>Productos solicitados</h2><span>{order.items.reduce((n,p)=>n+p.quantity,0)} unidades</span></div>{order.items.map(p=><article className="order-line" key={p.id}><span className="order-qty">{p.quantity} ×</span><div><h3>{p.name}</h3><p>{money(p.price)} por unidad</p></div><strong>{money(p.price*p.quantity)}</strong></article>)}</section></div><aside><section className="panel order-totals"><h2>Total del pedido</h2><p className="order-grand-total">{money(order.total)} <span>MXN</span></p><p className="hint">Total de productos. Envío y disponibilidad por confirmar.</p><div className="order-payment-note">Pago pendiente por transferencia o depósito. El negocio compartirá los datos de la cuenta.</div></section><section className="panel order-share no-print"><h2>Compartir con el negocio</h2><p>Envía únicamente el enlace por WhatsApp. Los productos, datos del cliente y total se consultan aquí.</p><Button asChild className="full" disabled={!url}><a href={url?`https://wa.me/${order.shop.phone}?text=${encodeURIComponent(url)}`:undefined} target="_blank" rel="noopener noreferrer"><Send/>Enviar enlace por WhatsApp</a></Button><Button className="full" variant="outline" onClick={copy} disabled={!url}><Link2/>Copiar enlace del pedido</Button><Button className="full" variant="outline" onClick={()=>window.print()}><Printer/>Imprimir / PDF</Button>{copied&&<p role="status">{copied}</p>}<p className="hint">Este enlace permite ver el pedido. Compártelo con el negocio.</p></section></aside></div><Button asChild variant="link" className="no-print"><a href={`/tienda/${order.shop.id}`}><ArrowLeft/>Volver al catálogo</a></Button></main></>;
}
