'use client';
import {useEffect,useState,FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import PermissionPicker from './permission-picker';
import {type AdminSection} from './admin-permissions';
import PasswordField from './password-field';
type Member={id:string,email:string,is_owner:number,permissions:AdminSection[]};
export default function AccountManager(){
 const [invitePermissions,setInvitePermissions]=useState<AdminSection[]>([]);
 const [user,setUser]=useState<Member|null>(null),[members,setMembers]=useState<Member[]>([]),[email,setEmail]=useState(''),[link,setLink]=useState(''),[currentPassword,setCurrent]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const res=await fetch('/api/admin-auth/me',{cache:'no-store'});if(!res.ok)throw new Error('No pudimos consultar los accesos.');const data=await res.json() as {user:Member|null,users:Member[]};setUser(data.user);setMembers(data.users||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function action(kind:string,data:unknown){setBusy(true);setError('');setMessage('');try{const res=await fetch('/api/admin-auth/'+kind,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await res.json() as {error:string,url:string};if(!res.ok)throw new Error(result.error);if(kind==='invite'){setLink(result.url);setMessage('Invitación creada para '+email+'. Vence en 24 horas.')}if(kind==='password'){setCurrent('');setPassword('');setMessage('Contraseña actualizada. Se cerraron las demás sesiones.')}if(kind==='permissions'){await load();setMessage('Permisos guardados. Se aplican desde la siguiente acción del usuario.')}if(kind==='revoke'){await load();setMessage('Acceso retirado.')}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="panel account-panel"><summary>Mi cuenta y administradores</summary><p>{user?.email}</p>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}<form onSubmit={(e:FormEvent)=>{e.preventDefault();void action('password',{currentPassword,password})}}><h3>Cambiar contraseña</h3><PasswordField label="Contraseña actual" required autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} maxLength={128}/><PasswordField label="Nueva contraseña" required minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/><Button disabled={busy}>Actualizar contraseña</Button></form>{!!user?.is_owner&&<><h3>Administradores con acceso</h3>{members.map(m=><div className="account-member permission-member" key={m.id}><strong>{m.email}{m.is_owner?' · Propietario':''}</strong>{m.is_owner?<p className="hint">Acceso completo a todas las secciones.</p>:<><PermissionPicker value={m.permissions} disabled={busy} onChange={permissions=>setMembers(prev=>prev.map(u=>u.id===m.id?{...u,permissions}:u))}/><div className="permission-actions"><Button type="button" disabled={busy} onClick={()=>void action('permissions',{id:m.id,permissions:m.permissions})}>Guardar permisos de {m.email}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>{if(confirm('¿Quitar el acceso a '+m.email+'?'))void action('revoke',{id:m.id})}}>Quitar acceso</Button></div></>}</div>)}<form onSubmit={e=>{e.preventDefault();void action('invite',{email,permissions:invitePermissions})}}><label>Invitar administrador<Input type="email" required value={email} onChange={e=>{setEmail(e.target.value);setLink('')}} placeholder="correo@ejemplo.com"/></label><PermissionPicker value={invitePermissions} onChange={setInvitePermissions} disabled={busy}/><p className="hint">Si no marcas ninguna sección, solo podrá cambiar su contraseña.</p><Button disabled={busy}>Crear invitación</Button></form>{link&&<label>Copia este enlace y compártelo solo con la persona invitada<Input readOnly value={link} onFocus={e=>e.target.select()}/></label>}</>}</details>
}
