'use client';
import {useEffect,useState,FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Member={id:string,email:string,is_owner:number};
export default function AccountManager(){
 const [user,setUser]=useState<Member|null>(null),[members,setMembers]=useState<Member[]>([]),[email,setEmail]=useState(''),[link,setLink]=useState(''),[currentPassword,setCurrent]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const res=await fetch('/api/admin-auth/me',{cache:'no-store'});if(!res.ok)throw new Error('No pudimos consultar los accesos.');const data=await res.json() as {user:Member|null,users:Member[]};setUser(data.user);setMembers(data.users||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function action(kind:string,data:unknown){setBusy(true);setError('');setMessage('');try{const res=await fetch('/api/admin-auth/'+kind,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await res.json() as {error:string,url:string};if(!res.ok)throw new Error(result.error);if(kind==='invite'){setLink(result.url);setMessage('Invitación creada para '+email+'. Vence en 24 horas.')}if(kind==='password'){setCurrent('');setPassword('');setMessage('Contraseña actualizada. Se cerraron las demás sesiones.')}if(kind==='revoke'){await load();setMessage('Acceso retirado.')}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="panel account-panel"><summary>Mi cuenta y administradores</summary><p>{user?.email}</p>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}<form onSubmit={(e:FormEvent)=>{e.preventDefault();void action('password',{currentPassword,password})}}><h3>Cambiar contraseña</h3><label>Contraseña actual<Input type="password" required autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} maxLength={128}/></label><label>Nueva contraseña<Input type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><Button disabled={busy}>Actualizar contraseña</Button></form>{!!user?.is_owner&&<><h3>Administradores con acceso</h3>{members.map(m=><div className="account-member" key={m.id}><span>{m.email}{m.is_owner?' · Propietario':''}</span>{!m.is_owner&&<Button type="button" variant="outline" disabled={busy} onClick={()=>{if(confirm('¿Quitar el acceso a '+m.email+'?'))void action('revoke',{id:m.id})}}>Quitar acceso</Button>}</div>)}<form onSubmit={e=>{e.preventDefault();void action('invite',{email})}}><label>Invitar administrador<Input type="email" required value={email} onChange={e=>{setEmail(e.target.value);setLink('')}} placeholder="correo@ejemplo.com"/></label><p className="hint">Tendrá acceso a productos, inventario, pedidos y promociones. Solo tú podrás administrar las cuentas.</p><Button disabled={busy}>Crear invitación</Button></form>{link&&<label>Copia este enlace y compártelo solo con la persona invitada<Input readOnly value={link} onFocus={e=>e.target.select()}/></label>}</>}</details>
}
