'use client';
import { useEffect,useState,FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction,AlertDialogFooter } from '@/components/ui/alert-dialog';
import { ShoppingBag,Plus,ArrowUpRight,Package,ImagePlus,Store,Link2,Pencil,Trash2,Check,LogOut,X } from 'lucide-react';
import { money,Product,Shop,api } from './shared';
import { demoProducts } from './demo';
import { usePageTools } from './webmcp';
export default function Admin({signedIn}:{signedIn:boolean}) {
 const [shop,setShop]=useState<Shop|null>(null),[products,setProducts]=useState<Product[]>([]),[name,setName]=useState(''),[phone,setPhone]=useState(''),[loading,setLoading]=useState(signedIn),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(false),[editing,setEditing]=useState<Product|null>(null),[removing,setRemoving]=useState<Product|null>(null),[pname,setPname]=useState(''),[price,setPrice]=useState(''),[desc,setDesc]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[formError,setFormError]=useState('');
 async function load(){setLoading(true);setError('');try{const d=await api('/api/shop');setShop(d.shop);setProducts(d.products);setName(d.shop?.name||'');setPhone(d.shop?.phone||'')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{if(signedIn)void load()},[signedIn]);
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 async function saveShop(e:FormEvent){e.preventDefault();setBusy(true);setError('');setStatus('');try{const d=await api('/api/shop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone})});setShop(d.shop);setStatus('Los datos de tu negocio están guardados.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function openProduct(p:Product|null){setEditing(p);setPname(p?.name||'');setPrice(p?String(p.price/100):'');setDesc(p?.description||'');setFile(null);setFormError('');setModal(true)}
 async function saveProduct(e:FormEvent){e.preventDefault();setBusy(true);setFormError('');try{const body=new FormData();body.set('name',pname);body.set('price',price);body.set('description',desc);if(file)body.set('image',file);if(editing)body.set('id',editing.id);const d=await api('/api/products',{method:'POST',body});setProducts(p=>editing?p.map(x=>x.id===editing.id?d.product:x):[d.product,...p]);setModal(false);setStatus(editing?'Producto actualizado.':'Producto agregado a tu tienda.')}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function removeProduct(){if(!removing)return;setBusy(true);setError('');try{await api('/api/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:removing.id})});setProducts(p=>p.filter(x=>x.id!==removing.id));setRemoving(null);setStatus('Producto eliminado.')}catch(e){setError((e as Error).message);setRemoving(null)}finally{setBusy(false)}}
 async function copyLink(){if(!shop)return;try{await navigator.clipboard.writeText(`${location.origin}/tienda/${shop.id}`);setStatus('Enlace copiado. Ya puedes enviarlo a tus compradores.')}catch{setStatus(`Tu enlace: ${location.origin}/tienda/${shop.id}`)}}
 usePageTools([{name:'start_product_creation',title:'Agregar producto',description:'Abre el formulario para cargar la foto, nombre, descripción y precio. No guarda un producto.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No se esperan parámetros.');if(!shop)throw new Error('Primero configura tu negocio.');openProduct(null);return {formOpened:true}}}]);
 return <><header className="topbar"><a className="brand" href="/"><ShoppingBag/>mi catálogo<span className="brand-dot">.</span></a><div className="top-actions"><a className="demo-link" href="/tienda/ejemplo">Ver tienda de ejemplo <ArrowUpRight size={15}/></a>{signedIn&&<a className="logout" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={16}/>Salir</a>}</div></header><main className="workspace"><div className="page-heading"><div><p className="eyebrow">ESPACIO DEL NEGOCIO</p><h1>Tu catálogo. Tus productos.</h1><p>Carga tus productos y comparte tu tienda para recibir pedidos.</p></div>{shop?<Button asChild variant="outline"><a href={`/tienda/${shop.id}`} target="_blank" rel="noopener"><ArrowUpRight/>Ver mi tienda</a></Button>:<Button variant="outline" disabled><ArrowUpRight/>Ver mi tienda</Button>}</div>
 {error&&<div className="error" role="alert">{error}{signedIn&&<Button variant="link" onClick={load}>Volver a cargar</Button>}</div>}{status&&<div className="status" role="status"><Check size={18}/>{status}</div>}
 <div className="admin-layout"><div><section className="panel setup"><div className="section-title"><div className="icon-tile"><Store/></div><div><h2>{shop?'Tu negocio':'Primero, tu negocio'}</h2><p>Así te verán tus compradores.</p></div></div><form onSubmit={saveShop}><fieldset disabled={!signedIn||loading||busy}><div className="form-grid"><label>Nombre del negocio<Input value={name} onChange={e=>setName(e.target.value)} required maxLength={80} placeholder="El nombre de tu marca"/></label><label>WhatsApp para pedidos<Input value={phone} onChange={e=>setPhone(e.target.value)} required type="tel" maxLength={30} placeholder="Ej. 52 811 234 5678"/></label></div><p className="hint">Incluye el código de país. Recibirás los pedidos en este número. Precios en MXN.</p>{signedIn&&<Button type="submit" disabled={busy||loading}>{loading?'Cargando…':busy?'Guardando…':shop?'Guardar cambios':'Guardar negocio'}</Button>}</fieldset>{!signedIn&&<><Button asChild><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Iniciar sesión con ChatGPT</a></Button><p className="hint login-hint">Solo tú administras tus productos. Tus compradores entran con el enlace, sin iniciar sesión.</p></>}</form></section>
 {shop&&<div className="share-bar"><div><Link2 size={20}/><span>Tu tienda ya tiene enlace propio</span></div><Button variant="outline" onClick={copyLink}>Copiar enlace</Button></div>}
 <section className="products-panel"><div className="section-title spread"><div><h2>Mis productos <span className="count">{products.length}</span></h2><p>Fotos, nombres y precios. Todo en un solo lugar.</p></div><Button disabled={!shop||loading} onClick={()=>openProduct(null)}><Plus/>Agregar producto</Button></div>{loading?<p className="hint" role="status">Cargando tu catálogo…</p>:products.length?<div className="admin-products">{products.map(p=><article className="admin-product" key={p.id}><img src={`/api/image/${p.image}`} alt={p.name} loading="lazy"/><div className="product-info"><h3>{p.name}</h3><p>{money(p.price)}</p><div className="product-actions"><Button variant="outline" size="sm" onClick={()=>openProduct(p)} aria-label={`Editar ${p.name}`}><Pencil size={14}/>Editar</Button><Button variant="ghost" size="icon" aria-label={`Eliminar ${p.name}`} onClick={()=>setRemoving(p)}><Trash2 size={16}/></Button></div></div></article>)}</div>:<Empty className="empty-catalog"><EmptyHeader><div className="empty-symbol"><Package size={32}/></div><EmptyTitle>Tu primer producto empieza aquí</EmptyTitle><EmptyDescription>{shop?'Agrega una foto, el nombre y el precio. Aparecerá al instante en tu tienda.':'Configura tu negocio y agrega una foto, el nombre y el precio de cada producto.'}</EmptyDescription></EmptyHeader>{shop&&<Button variant="outline" onClick={()=>openProduct(null)}><Plus/>Agregar mi primer producto</Button>}</Empty>}{!products.length&&<div className="demo-preview"><div className="section-title spread"><div><h2>Así puede verse tu tienda</h2><p>Productos de ejemplo para explorar la app.</p></div><a className="demo-link" href="/tienda/ejemplo">Probar carrito <ArrowUpRight size={15}/></a></div><div className="demo-products">{demoProducts.map(p=><a className="demo-product" href="/tienda/ejemplo" key={p.id}><img src={p.image} alt={p.name}/><span>Ejemplo</span><h3>{p.name}</h3><p>{money(p.price)}</p></a>)}</div></div>}</section></div>
 <aside className="guide"><p className="eyebrow">ASÍ DE SENCILLO</p><h2>Del catálogo<br/>al pedido.</h2><div className="step"><span>01</span><div><h3>Carga tus productos</h3><p>Agrega fotos y el precio que tú decidas.</p></div></div><div className="step"><span>02</span><div><h3>Comparte tu tienda</h3><p>Un enlace para que tus clientes elijan y llenen su carrito.</p></div></div><div className="step"><span>03</span><div><h3>Recibe el pedido</h3><p>Recibes un enlace por WhatsApp y abres el pedido completo en la página.</p></div></div><div className="guide-footer"><ShoppingBag size={18}/><p>Tú acuerdas el pago.<br/><strong>Sin cobros en la página.</strong></p></div></aside></div></main>
 <Dialog open={modal} onOpenChange={v=>{if(!busy)setModal(v)}}><DialogContent className="editor-dialog" showCloseButton={false}><div className="dialog-heading"><DialogTitle>{editing?'Editar producto':'Nuevo producto'}</DialogTitle><Button variant="ghost" size="icon" disabled={busy} onClick={()=>setModal(false)} aria-label="Cerrar"><X/></Button></div><DialogDescription>Una buena foto y un precio claro. Listo para tu catálogo.</DialogDescription><form onSubmit={saveProduct}><fieldset disabled={busy}><label className="upload-area">{preview||editing?.image?<img src={preview||`/api/image/${editing?.image}`} alt="Vista previa del producto"/>:<ImagePlus size={34}/>}<span>{file?file.name:editing?'Cambiar foto':'Subir foto del producto'}</span><small>JPG, PNG o WebP · Hasta 5 MB</small><input aria-label="Foto del producto" type="file" accept="image/jpeg,image/png,image/webp" required={!editing} onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>5*1024*1024){setFormError('La imagen debe pesar menos de 5 MB.');e.target.value='';setFile(null)}else{setFormError('');setFile(f||null)}}}/></label><label>Nombre del producto<Input required value={pname} onChange={e=>setPname(e.target.value)} maxLength={120} placeholder="Escribe el nombre del producto"/></label><label>Precio (MXN)<Input required type="number" inputMode="decimal" min="0.01" max="999999.99" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0.00"/></label><label>Descripción <span className="optional">(opcional)</span><Textarea value={desc} onChange={e=>setDesc(e.target.value)} maxLength={400} placeholder="Tamaño, material, presentación…"/></label></fieldset>{formError&&<p role="alert" className="error">{formError}</p>}<Button className="full" type="submit" disabled={busy}>{busy?'Guardando producto…':editing?'Guardar cambios':'Agregar a mi tienda'}</Button></form></DialogContent></Dialog>
 <AlertDialog open={!!removing} onOpenChange={v=>{if(!v&&!busy)setRemoving(null)}}><AlertDialogContent><AlertDialogTitle>¿Eliminar este producto?</AlertDialogTitle><AlertDialogDescription>“{removing?.name}” dejará de aparecer en tu tienda. Puedes volver a agregarlo después.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void removeProduct()}}>{busy?'Eliminando…':'Eliminar producto'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
