'use client';
import {useEffect,useState} from 'react';
import {BadgeCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from './shared';
type Profile={id:string,name:string,instagram:string,phone:string,status:string};
export default function CustomerVerification({shopId,onProfile}:{shopId:string,onProfile:(p:Profile)=>void}){
 const [open,setOpen]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){try{const d=await api<{profile:Profile|null}>('/api/verification?shopId='+encodeURIComponent(shopId));setProfile(d.profile);if(d.profile)onProfile(d.profile)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void refresh()},[shopId]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const body=new FormData(e.currentTarget);body.set('shopId',shopId);try{const d=await api<{profile:Profile}>('/api/verification',{method:'POST',body});setProfile(d.profile);onProfile(d.profile)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><Button variant="ghost" size="icon" aria-label="Verificar mi perfil" onClick={()=>{setOpen(true);void refresh()}}><BadgeCheck color={profile?.status==='approved'?'#167561':'#bb4307'}/></Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="editor-dialog"><DialogTitle>Verifica tu perfil</DialogTitle><DialogDescription>El negocio revisa tu solicitud y confirma o rechaza la verificación.</DialogDescription><p className="preview-banner">Prueba de ropa y accesorios: usa datos e imágenes ficticios.</p>{profile&&<section className="panel"><h3>{profile.status==='approved'?'✓ Perfil verificado':profile.status==='pending'?'Solicitud en revisión':'Solicitud rechazada o vencida'}</h3><p>{profile.name} · @{profile.instagram}</p><p className="hint">Te reconoceremos al pedir desde este navegador con el mismo nombre y teléfono. En otro dispositivo necesitarás volver a verificarte.</p><Button variant="outline" onClick={refresh}>Actualizar estado</Button></section>}{(!profile||profile.status==='rejected')&&<form onSubmit={submit}><fieldset disabled={busy}><label>Nombre completo<Input name="name" required maxLength={80} autoComplete="name"/></label><label>Instagram<Input name="instagram" required maxLength={31} placeholder="@tuusuario"/></label><label>Teléfono<Input name="phone" required type="tel" autoComplete="tel"/></label><label>Imagen de INE (ficticia en esta prueba)<Input name="ine" type="file" accept="image/jpeg,image/png" required/></label><label>Selfie (imagen de muestra)<Input name="selfie" type="file" accept="image/jpeg,image/png" required/></label><p className="hint">JPG o PNG, hasta 5 MB por imagen. Solo los administradores con permiso pueden revisarlas. Se borran al resolver la solicitud; si vence después de 7 días, se eliminan en la siguiente consulta. No hacemos reconocimiento facial automático.</p><label className="verification-consent"><input name="consent" value="yes" type="checkbox" required/>Acepto que el negocio revise manualmente estos datos e imágenes para verificar mi perfil.</label></fieldset><Button className="full" disabled={busy} type="submit">{busy?'Enviando…':'Enviar solicitud'}</Button></form>}{error&&<p role="alert" className="error">{error}</p>}</DialogContent></Dialog></>
}
