'use client';
import {useEffect,useState} from 'react';
import {Smartphone,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};
export default function InstallApp({shopId}:{shopId:string}){
 const [prompt,setPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(true),[instructions,setInstructions]=useState(false),[ios,setIos]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const mode=window.matchMedia('(display-mode: standalone)');const update=()=>setInstalled(mode.matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone));update();setIos(/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1));const capture=(event:Event)=>{event.preventDefault();setPrompt(event as InstallPrompt)};const complete=()=>{setInstalled(true);setPrompt(null)};window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',complete);mode.addEventListener('change',update);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js',{scope:'/tienda/'+shopId}).catch(()=>{});return()=>{window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('appinstalled',complete);mode.removeEventListener('change',update)}},[shopId]);
 async function install(){if(!prompt){setInstructions(v=>!v);return}setBusy(true);setMessage('');try{await prompt.prompt();const result=await prompt.userChoice;setPrompt(null);if(result.outcome==='accepted')setInstalled(true)}catch{setInstructions(true);setMessage('Puedes instalarla desde el menú de tu navegador.')}finally{setBusy(false)}}
 if(installed)return null;
 return <section className="install-app"><Smartphone aria-hidden="true"/><div><h3>Lleva tu catálogo en el celular</h3><p>Ábrelo desde tu pantalla de inicio, como una app.</p><Button onClick={install} disabled={busy} aria-expanded={prompt?undefined:instructions}><Download aria-hidden="true"/>{busy?'Abriendo…':'Instalar app'}</Button>{instructions&&<div className="install-steps">{ios?<p>Abre este catálogo en Safari. Toca Compartir → Agregar a pantalla de inicio. Activa «Abrir como app web» si aparece y toca Agregar.</p>:<p>Abre este catálogo en Chrome o Edge. En el menú del navegador, elige «Instalar app» o «Agregar a pantalla de inicio». Si estás dentro de WhatsApp, ábrelo primero en tu navegador.</p>}<p>Necesitas conexión para consultar existencias y enviar pedidos.</p></div>}{message&&<p role="status">{message}</p>}</div></section>
}
