 'use client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import type {OptionGroup} from './shared';
export default function OptionsEditor({groups,onChange}:{groups:OptionGroup[],onChange:(groups:OptionGroup[])=>void}){
 function update(id:string,patch:Partial<OptionGroup>){onChange(groups.map(g=>g.id===id?{...g,...patch}:g))}
 return <section className="options-editor"><h3>Opciones del producto</h3><p className="hint">Agrega Color, Talla, Presentación u otro nombre. Oculta un grupo si no aplica. El precio final es el precio base más los ajustes elegidos.</p>{groups.map(g=><div className="option-group-editor" key={g.id}><label>Nombre del grupo<Input required maxLength={40} value={g.label} onChange={e=>update(g.id,{label:e.target.value})} placeholder="Ej. Color"/></label><label className="inline-check"><Checkbox checked={g.visible} onCheckedChange={v=>update(g.id,{visible:v===true})}/>Mostrar al cliente</label>{g.values.map(v=><div className="option-value-editor" key={v.id}><label>Opción<Input required maxLength={80} value={v.label} onChange={e=>update(g.id,{values:g.values.map(x=>x.id===v.id?{...x,label:e.target.value}:x)})} placeholder="Ej. Azul o Grande"/></label><label>Ajuste local (MXN)<Input required type="number" step="0.01" value={Number.isFinite(v.adjustment)?v.adjustment/100:''} onChange={e=>update(g.id,{values:g.values.map(x=>x.id===v.id?{...x,adjustment:e.target.value===''?NaN:Math.round(Number(e.target.value)*100)}:x)})}/></label><label>Ajuste paquetería (MXN)<Input type="number" step="0.01" placeholder="Igual al local" value={v.shippingAdjustment===undefined?'':v.shippingAdjustment/100} onChange={e=>update(g.id,{values:g.values.map(x=>x.id===v.id?{...x,shippingAdjustment:e.target.value===''?undefined:Math.round(Number(e.target.value)*100)}:x)})}/></label><Button type="button" variant="ghost" disabled={g.values.length===1} aria-label={`Quitar opción ${v.label||'sin nombre'}`} onClick={()=>update(g.id,{values:g.values.filter(x=>x.id!==v.id)})}>Quitar</Button></div>)}<p className="hint">0 conserva el precio. 50 suma $50. −20 resta $20.</p><div className="option-editor-actions"><Button type="button" variant="outline" disabled={g.values.length>=20} onClick={()=>update(g.id,{values:[...g.values,{id:crypto.randomUUID(),label:'',adjustment:0}]})}>Agregar opción</Button><Button type="button" variant="ghost" onClick={()=>onChange(groups.filter(x=>x.id!==g.id))}>Eliminar grupo</Button></div></div>)}<Button type="button" variant="outline" disabled={groups.length>=3} onClick={()=>onChange([...groups,{id:crypto.randomUUID(),label:groups.length===0?'Color':groups.length===1?'Talla':'Presentación',visible:true,values:[{id:crypto.randomUUID(),label:'',adjustment:0}]}])}>Agregar grupo de opciones</Button></section>
}
