 'use client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import type {OptionGroup} from './shared';
export default function OptionsEditor({groups,onChange,basePrice,shippingPrice}:{basePrice:number,shippingPrice:number,groups:OptionGroup[],onChange:(groups:OptionGroup[])=>void}){
 function finalValues(g:OptionGroup){return g.values.map(v=>g.pricing==='final'?v:{...v,adjustment:v.adjustment===0?0:basePrice+v.adjustment,...(v.shippingAdjustment===undefined?{}:{shippingAdjustment:shippingPrice+v.shippingAdjustment})})}
 function update(id:string,patch:Partial<OptionGroup>){onChange(groups.map(g=>g.id===id?{...g,...patch}:g))}
 return <section className="options-editor"><h3>Opciones del producto</h3><p className="hint">Agrega Color, Talla, Presentación u otro nombre. Oculta un grupo si no aplica. Escribe el precio FINAL de cada opción. No se suma al precio del producto. Pon los precios en un solo grupo (por ejemplo Bolsa); los demás pueden quedar vacíos.</p>{groups.map(g=><div className="option-group-editor" key={g.id}><label>Nombre del grupo<Input required maxLength={40} value={g.label} onChange={e=>update(g.id,{label:e.target.value})} placeholder="Ej. Color"/></label><label className="inline-check"><Checkbox checked={g.visible} onCheckedChange={v=>update(g.id,{visible:v===true})}/>Mostrar al cliente</label>{g.values.map(v=><div className="option-value-editor" key={v.id}><label>Opción<Input required maxLength={80} value={v.label} onChange={e=>update(g.id,{values:g.values.map(x=>x.id===v.id?{...x,label:e.target.value}:x)})} placeholder="Ej. Azul o Grande"/></label><label>Precio final local (MXN)<Input type="number" min="0.01" step="0.01" placeholder="Precio del producto" value={Number.isFinite(v.adjustment)&&v.adjustment!==0?(g.pricing==='final'?v.adjustment:basePrice+v.adjustment)/100:''} onChange={e=>update(g.id,{pricing:'final',values:finalValues(g).map(x=>x.id===v.id?{...x,adjustment:e.target.value===''?0:Math.round(Number(e.target.value)*100)}:x)})}/></label><label>Precio final paquetería (MXN)<Input type="number" min="0.01" step="0.01" placeholder="Igual al local" value={v.shippingAdjustment===undefined?'':(g.pricing==='final'?v.shippingAdjustment:shippingPrice+v.shippingAdjustment)/100} onChange={e=>update(g.id,{pricing:'final',values:finalValues(g).map(x=>x.id===v.id?{...x,shippingAdjustment:e.target.value===''?undefined:Math.round(Number(e.target.value)*100)}:x)})}/></label><Button type="button" variant="ghost" disabled={g.values.length===1} aria-label={`Quitar opción ${v.label||'sin nombre'}`} onClick={()=>update(g.id,{values:g.values.filter(x=>x.id!==v.id)})}>Quitar</Button></div>)}<p className="hint">Ejemplo: 299 significa $299 en total. Vacío utiliza el precio del producto.</p><div className="option-editor-actions"><Button type="button" variant="outline" disabled={g.values.length>=20} onClick={()=>update(g.id,{values:[...g.values,{id:crypto.randomUUID(),label:'',adjustment:0}]})}>Agregar opción</Button><Button type="button" variant="ghost" onClick={()=>onChange(groups.filter(x=>x.id!==g.id))}>Eliminar grupo</Button></div></div>)}<Button type="button" variant="outline" disabled={groups.length>=3} onClick={()=>onChange([...groups,{pricing:'final',id:crypto.randomUUID(),label:groups.length===0?'Color':groups.length===1?'Talla':'Presentación',visible:true,values:[{id:crypto.randomUUID(),label:'',adjustment:0}]}])}>Agregar grupo de opciones</Button></section>
}
