 'use client';
import OrderEditor from './order-editor';
import {useEffect,useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api,money,fulfillmentLabel,fulfillmentCity} from './shared';
import type {OrderSummary} from './order-types';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Monterrey',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default function OrdersDashboard({initialDate}:{initialDate?:string}){
 const [date,setDate]=useState(initialDate||today()),[orders,setOrders]=useState<OrderSummary[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[exporting,setExporting]=useState(false),[saving,setSaving]=useState('');const request=useRef(0);
 useEffect(()=>{const select=(e:Event)=>setDate((e as CustomEvent<string>).detail);window.addEventListener('show-orders-day',select);return()=>window.removeEventListener('show-orders-day',select)},[]);
 async function load(day:string){const current=++request.current;setLoading(true);setError('');setOrders([]);try{let offset:number|null=0;const all:OrderSummary[]=[];while(offset!==null){const d: {orders:OrderSummary[],nextOffset:number|null}=await api(`/api/orders/daily?date=${encodeURIComponent(day)}&offset=${offset}`);if(current!==request.current)return;all.push(...d.orders);offset=d.nextOffset}setOrders(all)}catch(e){if(current===request.current)setError((e as Error).message)}finally{if(current===request.current)setLoading(false)}}
 useEffect(()=>{void load(date);return()=>{request.current++}},[date]);
 async function setPayment(o:OrderSummary){setSaving(o.id);setError('');try{await api('/api/orders/payment',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:o.id,status:o.status==='paid'?'pending':'paid'})});await load(date);window.dispatchEvent(new Event('orders-payment-changed'))}catch(e){setError((e as Error).message)}finally{setSaving('')}}
 async function download(format:'pdf'|'xlsx'){setExporting(true);setError('');try{const {exportOrders}=await import('./orders-export');await exportOrders(orders,date,format)}catch{setError('No se pudo descargar el archivo. Inténtalo de nuevo.')}finally{setExporting(false)}}
 return <section className="panel orders-dashboard"><div className="section-title spread"><div><h2>Pedidos del día</h2><p>Solo tú puedes ver esta lista. Horario de Monterrey.</p></div><label>Fecha<Input type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label></div><div className="dashboard-actions"><Button variant="outline" disabled={loading} onClick={()=>load(date)}>Actualizar lista</Button><Button variant="outline" disabled={loading||exporting||!orders.length} onClick={()=>download('pdf')}>Descargar PDF</Button><Button variant="outline" disabled={loading||exporting||!orders.length} onClick={()=>download('xlsx')}>Descargar Excel</Button></div>{error&&<p role="alert" className="error">{error}</p>}{loading?<p role="status">Cargando pedidos…</p>:<><div className="orders-stats"><span><strong>{orders.length}</strong> pedidos</span><span>Total de pedidos: <strong>{money(orders.reduce((n,o)=>n+o.total,0))}</strong></span></div><p className="hint">Ventas pagadas: {money(orders.filter(o=>o.status==='paid').reduce((n,o)=>n+o.total,0))}. Solo los pagos registrados se contabilizan como ventas.</p>{!orders.length?<p>No hay pedidos para esta fecha.</p>:<div className="daily-orders">{orders.map(o=><article key={o.id}><div><h3>{o.customer}</h3>{o.verification?.status==='approved'&&<span className="status">✓ Cliente verificado al realizar el pedido</span>}<p>{new Date(o.date).toLocaleTimeString('es-MX',{timeZone:'America/Monterrey',hour:'2-digit',minute:'2-digit'})} · {o.id.slice(0,8).toUpperCase()} · {fulfillmentCity(o.fulfillment)}</p><p>{o.phone} · {o.address}</p><p>{o.items.map(p=>`${p.quantity} × ${p.name}${p.options?.length?' ('+p.options.join(', ')+')':''} · ${p.department||'Sin departamento registrado'} · ${money(p.price)} c/u`).join(' · ')}</p></div><div><OrderEditor id={o.id} onSaved={()=>load(date)}/><strong>{money(o.total)}</strong><span className="payment-state">{o.status==='paid'?'Pagado':'Pendiente de pago'}</span><Button disabled={!!saving} variant={o.status==='paid'?'outline':'default'} onClick={()=>setPayment(o)}>{saving===o.id?'Guardando…':o.status==='paid'?'Corregir a pendiente':'Marcar como pagado'}</Button><Button variant="outline" asChild><a href={`/pedido/${o.token}`} target="_blank" rel="noopener">Ver pedido</a></Button></div></article>)}</div>}</>}{exporting&&<p role="status">Preparando archivo…</p>}</section>
}
