import type {OrderSummary} from './order-types';
import {money,fulfillmentCity} from './shared';
function save(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const dateTime=(s:string)=>new Date(s).toLocaleString('es-MX',{timeZone:'America/Monterrey',dateStyle:'short',timeStyle:'short'});
export async function buildOrderExport(orders:OrderSummary[],date:string,format:'pdf'|'xlsx'){
 const columns=['Fecha y hora','Número de pedido','Cliente','Teléfono','Ciudad / cobertura','Dirección','Productos y opciones','Subtotal MXN','Descuento MXN','Envío MXN','Total MXN','Código','Notas','Estado'];
 const rows=orders.map(o=>[dateTime(o.date),o.id.slice(0,8).toUpperCase(),o.customer,o.phone,fulfillmentCity(o.fulfillment),o.address,o.items.map(p=>`${p.quantity} × ${p.name}${p.options?.length?' ('+p.options.join(', ')+')':''} · ${p.department||'No registrado'} · ${money(p.price)} c/u`).join('\n'),(o.subtotal??o.items.reduce((n,p)=>n+p.quantity*p.price,0))/100,(o.discount??0)/100,o.shippingFee===undefined?'Por confirmar':o.shippingFee/100,o.total/100,o.couponCode||'',o.notes,'Pendiente de pago']);
 const detailColumns=['Fecha y hora','Número de pedido','Cliente','Teléfono','Ciudad / cobertura','Producto','Departamento','Opciones','Precio vendido MXN','Cantidad','Importe MXN'];
 const detailRows=orders.flatMap(o=>o.items.map(p=>[dateTime(o.date),o.id.slice(0,8).toUpperCase(),o.customer,o.phone,fulfillmentCity(o.fulfillment),p.name,p.department||'No registrado',p.options?.join(' · ')||'',p.price/100,p.quantity,p.price*p.quantity/100]));
 if(format==='xlsx'){
  const {default:ExcelJS}=await import('exceljs');const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet('Pedidos');sheet.addRow(columns);rows.forEach(row=>sheet.addRow(row));sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:'A1',to:'N1'};sheet.columns.forEach((c,i)=>{c.width=[23,20,25,20,24,40,60,18,18,18,18,18,40,22][i]});
  const details=workbook.addWorksheet('Detalle de productos');details.addRow(detailColumns);detailRows.forEach(row=>details.addRow(row));details.columns.forEach((c,i)=>{c.width=[23,20,25,20,24,35,24,40,22,12,20][i]});details.views=[{state:'frozen',ySplit:1}];details.autoFilter={from:'A1',to:'K1'};
  for(const ws of [sheet,details]){ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF174F43'}};ws.eachRow((row,i)=>{row.alignment={vertical:'top',wrapText:true};if(i>1)for(const n of ws===sheet?[8,9,10,11]:[9,11])row.getCell(n).numFmt='"$"#,##0.00'})}
  const total=sheet.addRow(['','','','','','','Total',...([7,8,9,10].map(i=>rows.reduce((sum,r)=>sum+(typeof r[i]==='number'?r[i] as number:0),0)))]);total.font={bold:true};for(const n of [8,9,10,11])total.getCell(n).numFmt='"$"#,##0.00';
  const buffer=await workbook.xlsx.writeBuffer();return new Blob([buffer as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
 }
 const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const doc=new jsPDF({orientation:'landscape',format:'a4'});doc.setFontSize(17);doc.text(`Pedidos del ${date}`,14,17);doc.setFontSize(10);doc.text(`${orders.length} pedidos · Total: ${money(orders.reduce((n,o)=>n+o.total,0))} MXN · Pendientes de pago`,14,25);
 const footer=()=>{doc.setFontSize(8);doc.text(`Uso interno · Página ${doc.getNumberOfPages()}`,14,202)};
 autoTable(doc,{startY:32,head:[['Fecha / hora','N.º pedido','Cliente','Teléfono','Ciudad','Producto / opciones','Departamento','Precio vendido','Cant.','Importe']],body:detailRows.map(r=>[r[0],r[1],r[2],r[3],r[4],`${r[5]}${r[7]?'\n'+r[7]:''}`,r[6],money(Number(r[8])*100),r[9],money(Number(r[10])*100)]),styles:{fontSize:7,cellPadding:2,overflow:'linebreak'},headStyles:{fillColor:[23,79,67]},columnStyles:{0:{cellWidth:25},1:{cellWidth:21},2:{cellWidth:28},3:{cellWidth:24},4:{cellWidth:25},5:{cellWidth:60},6:{cellWidth:27},7:{cellWidth:24},8:{cellWidth:12},9:{cellWidth:23}},margin:{left:14,right:14,bottom:15},didDrawPage:footer});
 const y=(doc as unknown as {lastAutoTable:{finalY:number}}).lastAutoTable.finalY+12;
 autoTable(doc,{startY:y,head:[['N.º pedido','Dirección / Notas','Productos MXN','Descuento MXN','Envío MXN','Total MXN']],body:orders.map(o=>[o.id.slice(0,8).toUpperCase(),`${o.address}${o.notes?'\n'+o.notes:''}`,money(o.subtotal??o.items.reduce((n,p)=>n+p.price*p.quantity,0)),`${money(o.discount||0)}${o.couponCode?' ('+o.couponCode+')':''}`,o.shippingFee===undefined?'Por confirmar':money(o.shippingFee),money(o.total)]),styles:{fontSize:8,cellPadding:3,overflow:'linebreak'},headStyles:{fillColor:[23,79,67]},margin:{left:14,right:14,bottom:15},didDrawPage:footer});return new Blob([doc.output('arraybuffer')],{type:'application/pdf'});
}
export async function exportOrders(orders:OrderSummary[],date:string,format:'pdf'|'xlsx'){save(await buildOrderExport(orders,date,format),`pedidos-${date}.${format}`)}
