'use client';
import {useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api,money,Product} from './shared';
import {ImportRow,ImportedProduct,prepareImport,normalizedProductName} from './product-import-data';
export default function ProductImporter({products,onImported}:{products:Product[],onImported:(p:Product[])=>void}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<ImportRow[]>([]),[preview,setPreview]=useState<ImportedProduct[]>([]),[errors,setErrors]=useState<string[]>([]),[busy,setBusy]=useState(false),[reading,setReading]=useState(false),[filename,setFilename]=useState(''),[status,setStatus]=useState('');const key=useRef('');
 async function read(file?:File){setRows([]);setPreview([]);setErrors([]);setStatus('');setFilename(file?.name||'');if(!file)return;setReading(true);try{const {readProductExcel}=await import('./product-import-excel');const d=await readProductExcel(file),parsed=prepareImport(d.rows),names=new Set(products.map(p=>normalizedProductName(p.name)));const duplicates=parsed.products.filter(p=>names.has(normalizedProductName(p.name))).map(p=>`${p.name}: ya existe en tu catálogo. Usa Editar producto o cambia el nombre.`);setRows(d.rows);setPreview(parsed.products);setErrors([...d.errors,...parsed.errors,...duplicates]);key.current=crypto.randomUUID()}catch(e){setErrors([(e as Error).message])}finally{setReading(false)}}
 async function template(){setReading(true);setErrors([]);try{const {productTemplate}=await import('./product-import-excel');const url=URL.createObjectURL(await productTemplate()),a=document.createElement('a');a.href=url;a.download='plantilla-productos.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setErrors(['No se pudo descargar la plantilla. Inténtalo de nuevo.'])}finally{setReading(false)}}
 async function save(){setBusy(true);setErrors([]);try{const d=await api<{count:number,products:Product[]}>('/api/products/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows,requestKey:key.current})});onImported(d.products);setStatus(`${d.count} productos importados. Puedes agregar sus fotos desde Editar producto.`);setRows([]);setPreview([]);setFilename('')}catch(e){setErrors([(e as Error).message])}finally{setBusy(false)}}
 return <><Button variant="outline" onClick={()=>setOpen(true)}>Importar Excel</Button><Dialog open={open} onOpenChange={v=>{if(!busy&&!reading)setOpen(v)}}><DialogContent className="import-dialog"><DialogTitle>Importar productos desde Excel</DialogTitle><DialogDescription>Una fila por talla o color. Las filas con el mismo nombre se agrupan en un producto.</DialogDescription><Button variant="outline" disabled={busy||reading} onClick={template}>Descargar plantilla Excel</Button><label className="import-upload">Subir archivo .xlsx<input type="file" accept=".xlsx" disabled={busy||reading} onChange={e=>{void read(e.target.files?.[0]);e.target.value=''}}/></label><p className="hint">Hasta 100 filas y 5 MB. Los precios son por producto: local para MTY/CDMX y por paquetería para envíos. El envío de $300 se agrega por pedido. Los productos nuevos estarán disponibles en las tres opciones y podrás agregar sus fotos después.</p>{reading&&<p role="status">Leyendo archivo…</p>}{status&&<p className="status" role="status">{status}</p>}{errors.length>0&&<div className="error" role="alert"><strong>Corrige el archivo antes de importar:</strong><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}{preview.length>0&&<><h3>{filename}: {rows.length} filas → {preview.length} productos</h3><div className="import-preview">{preview.map((p,i)=><article key={i}><strong>{p.name}</strong><p>{p.department} · {p.category}</p>{p.options.length?p.options[0].values.map(v=><p key={v.id}>{v.label} — Local {money(p.price+v.adjustment)} · Paquetería {money(p.shippingPrice+(v.shippingAdjustment??v.adjustment))}</p>):<p>Local {money(p.price)} · Paquetería {money(p.shippingPrice)}</p>}</article>)}</div><Button disabled={busy||reading||errors.length>0} onClick={save}>{busy?'Importando…':`Confirmar importación de ${preview.length} productos`}</Button></>}</DialogContent></Dialog></>;
}
