import type {OptionGroup} from './shared';
export type ImportRow={row:number,name:string,size:string,color:string,localPrice:number,shippingPrice:number,department:string,category:string,description:string};
export type ImportedProduct={name:string,price:number,shippingPrice:number,department:string,category:string,description:string,options:OptionGroup[]};
const norm=(s:string)=>s.trim().normalize('NFKC').toLocaleLowerCase('es-MX');
export function prepareImport(input:unknown):{products:ImportedProduct[],errors:string[]}{
 const errors:string[]=[];if(!Array.isArray(input)||!input.length||input.length>100)return {products:[],errors:['Incluye entre 1 y 100 filas por archivo.']};
 const groups=new Map<string,ImportRow[]>();
 for(const item of input){const r=item as ImportRow;const n=Number.isInteger(r?.row)?r.row:'?';if(!r||!Number.isInteger(r.row)||r.row<2||typeof r.name!=='string'||!r.name.trim()||r.name.length>120||!['size','color','department','category','description'].every(k=>typeof r[k as keyof ImportRow]==='string')||r.size.length>40||r.color.length>40||r.department.length>50||r.category.length>50||r.description.length>400||![r.localPrice,r.shippingPrice].every(p=>Number.isSafeInteger(p)&&p>=1&&p<=99999999)){errors.push(`Fila ${n}: revisa nombre, textos y precios (mayores a cero, máximo dos decimales).`);continue}const key=norm(r.name);groups.set(key,[...(groups.get(key)||[]),{...r,name:r.name.trim(),size:r.size.trim(),color:r.color.trim(),department:r.department.trim()||'General',category:r.category.trim()||'General',description:r.description.trim()}])}
 const products:ImportedProduct[]=[];
 for(const rows of groups.values()){const first=rows[0],hasSize=rows.some(r=>r.size),hasColor=rows.some(r=>r.color);if(rows.some(r=>r.department!==first.department||r.category!==first.category||r.description!==first.description)){errors.push(`${first.name}: usa el mismo departamento, categoría y descripción en todas sus filas.`);continue}if(rows.length>20){errors.push(`${first.name}: máximo 20 combinaciones por producto.`);continue}if(rows.some(r=>(hasSize&&!r.size)||(hasColor&&!r.color))){errors.push(`${first.name}: completa ${hasSize&&hasColor?'talla y color':hasSize?'talla':'color'} en todas sus filas.`);continue}const seen=new Set<string>();if(rows.some(r=>{const key=JSON.stringify([norm(r.size),norm(r.color)]);if(seen.has(key))return true;seen.add(key);return false})){errors.push(`${first.name}: hay filas con la misma talla y color. Deja una sola fila por combinación.`);continue}
 const price=Math.min(...rows.map(r=>r.localPrice)),shippingPrice=Math.min(...rows.map(r=>r.shippingPrice));const options:OptionGroup[]=hasSize||hasColor?[{id:'import-options',label:hasSize&&hasColor?'Talla / Color':hasSize?'Talla':'Color',visible:true,values:rows.map((r,i)=>({id:'option-'+i,label:hasSize&&hasColor?`${r.size} · ${r.color}`:r.size||r.color,adjustment:r.localPrice-price,shippingAdjustment:r.shippingPrice-shippingPrice}))}]:[];
 if(options.some(g=>g.values.some(v=>v.label.length>80))){errors.push(`${first.name}: acorta los nombres de talla y color.`);continue}products.push({name:first.name,price,shippingPrice,department:first.department,category:first.category,description:first.description,options})}
 return {products,errors};
}
export const normalizedProductName=norm;
