'use client';
import {useRef,useState} from 'react';
import {ZoomIn,ZoomOut,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
export default function ProductImageViewer({src,name}:{src:string,name:string}){
 const area=useRef<HTMLDivElement>(null),pointers=useRef(new Map<number,{x:number,y:number}>()),previous=useRef<{x:number,y:number,distance:number}|null>(null);
 const [view,setView]=useState({scale:1,x:0,y:0});
 function constrain(scale:number,x:number,y:number){const box=area.current?.getBoundingClientRect();const s=Math.min(4,Math.max(1,scale)),maxX=(box?.width||0)*(s-1)/2,maxY=(box?.height||0)*(s-1)/2;return {scale:s,x:Math.max(-maxX,Math.min(maxX,x)),y:Math.max(-maxY,Math.min(maxY,y))}}
 function zoom(delta:number){setView(v=>constrain(v.scale+delta,v.x,v.y))}
 function measurement(){const points=[...pointers.current.values()];if(!points.length)return null;const a=points[0],b=points[1]||a;return {x:(a.x+b.x)/2,y:(a.y+b.y)/2,distance:points.length>1?Math.hypot(a.x-b.x,a.y-b.y):0}}
 return <div className="product-photo-viewer"><div className="product-zoom-stage" ref={area} style={{cursor:view.scale>1?'grab':'zoom-in'}} onDoubleClick={()=>setView(v=>v.scale===1?constrain(2,0,0):constrain(1,0,0))} onPointerDown={e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});previous.current=measurement()}} onPointerMove={e=>{if(!pointers.current.has(e.pointerId))return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const now=measurement(),before=previous.current;if(now&&before)setView(v=>constrain(before.distance>0&&now.distance>0?v.scale*now.distance/before.distance:v.scale,v.x+now.x-before.x,v.y+now.y-before.y));previous.current=now}} onPointerUp={e=>{pointers.current.delete(e.pointerId);previous.current=measurement()}} onPointerCancel={e=>{pointers.current.delete(e.pointerId);previous.current=measurement()}} onLostPointerCapture={e=>{pointers.current.delete(e.pointerId);previous.current=measurement()}}><img src={src} alt={name} draggable={false} style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.scale})`}}/></div><div className="product-zoom-tools"><Button type="button" variant="outline" size="icon" disabled={view.scale<=1} aria-label="Reducir zoom" onClick={()=>zoom(-.5)}><ZoomOut/></Button><span aria-live="polite">{Math.round(view.scale*100)}%</span><Button type="button" variant="outline" size="icon" disabled={view.scale>=4} aria-label="Ampliar foto" onClick={()=>zoom(.5)}><ZoomIn/></Button><Button type="button" variant="ghost" aria-label="Restablecer foto" onClick={()=>setView({scale:1,x:0,y:0})}><RotateCcw size={18}/>Restablecer</Button></div><p className="product-zoom-hint">Amplía con los botones o con dos dedos. Arrastra para ver los detalles.</p></div>
}
