'use client';
import {useEffect,useState} from 'react';import {Button} from '@/components/ui/button';import {Bell} from 'lucide-react';import {api} from './shared';
export default function PushOptIn({shopId}:{shopId:string}){
 const [supported,setSupported]=useState(false),[active,setActive]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const scope='/tienda/'+shopId;
 useEffect(()=>{setSupported('serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window);if('serviceWorker' in navigator)navigator.serviceWorker.getRegistration(scope).then(async r=>{if(!r||!r.scope.endsWith(scope))return;const s=await r.pushManager.getSubscription();if(s){const d=await api<{active:boolean}>('/api/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shopId,subscription:s.toJSON(),action:'status'})});setActive(d.active)}}).catch(()=>{})},[shopId]);
 async function toggle(){setBusy(true);setMessage('');try{if(active){const r=await navigator.serviceWorker.getRegistration(scope),s=await r?.pushManager.getSubscription();if(s){await api('/api/push/subscribe',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({shopId,subscription:s.toJSON()})});await s.unsubscribe()}setActive(false);setMessage('Notificaciones desactivadas.');return}const permission=await Notification.requestPermission();if(permission!=='granted'){setMessage('Activa el permiso de notificaciones en los ajustes del navegador si quieres recibir avisos.');return}const {publicKey}=await api<{publicKey:string}>('/api/push/config');const r=await navigator.serviceWorker.register('/sw.js',{scope});if(!r.active)await new Promise<void>((resolve,reject)=>{const w=r.installing||r.waiting;if(!w)return reject(new Error('Recarga la página para activar las notificaciones.'));w.addEventListener('statechange',()=>{if(w.state==='activated')resolve();if(w.state==='redundant')reject(new Error('No se pudo activar el servicio.'))})});const binary=atob(publicKey.replace(/-/g,'+').replace(/_/g,'/')),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));const subscription=await r.pushManager.getSubscription()||await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await api('/api/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shopId,subscription:subscription.toJSON()})});setActive(true);setMessage('Listo. Recibirás novedades de esta tienda en este dispositivo.')}catch(e){setMessage((e as Error).message||'No se pudieron activar las notificaciones.')}finally{setBusy(false)}}
 return <section className="push-opt-in"><div><Bell size={21}/><div><h3>Novedades en tu dispositivo</h3><p>Recibe promociones como notificaciones. Puedes desactivarlas cuando quieras.</p></div></div>{supported?<Button variant="outline" disabled={busy} onClick={toggle}>{busy?'Un momento…':active?'Desactivar notificaciones':'Activar notificaciones'}</Button>:<p className="hint">En iPhone, abre el catálogo en Safari, agrégalo a la pantalla de inicio y ábrelo desde ese icono. En otros dispositivos, usa un navegador compatible.</p>}{message&&<p role="status">{message}</p>}</section>
}
