 'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Plus,Minus,Expand,X} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProductImageViewer from './product-image-viewer';
import {Product,money,imageUrl,Fulfillment,stockFor} from './shared';
import {Choices,CartEntry,visibleGroups,resolveSelection} from './product-options';
export default function StoreProductCard({product:p,fulfillment,cart,onAdd,onChange}:{product:Product,fulfillment:Fulfillment,cart:Record<string,CartEntry>,onAdd:(p:Product,choices:Choices)=>void,onChange:(key:string,delta:number)=>void}){
 const [open,setOpen]=useState(false);
 const [choices,setChoices]=useState<Choices>({});const groups=visibleGroups(p);let selected:ReturnType<typeof resolveSelection>|null=null;try{selected=resolveSelection(p,choices,fulfillment)}catch{}
 const remaining=selected?stockFor(p,selected.key,fulfillment):Infinity;const quantity=selected?cart[selected.key]?.quantity||0:0;const minPrice=(fulfillment==='shipping'?(p.shippingPrice??p.price):p.price)+groups.reduce((n,g)=>n+Math.min(...g.values.map(v=>fulfillment==='shipping'?(v.shippingAdjustment??v.adjustment):v.adjustment)),0);
 const details=(expanded=false)=><div className={expanded?'product-detail-info':'product-info'}>{expanded?<><p className="product-detail-taxonomy">{p.department}{p.category&&p.category!==p.department?` / ${p.category}`:''}</p><DialogTitle className="product-detail-name">{p.name}</DialogTitle><DialogDescription className="product-detail-description">{p.description||'Elige tus opciones y agrega este producto a tu pedido.'}</DialogDescription></>:<h3>{p.name}</h3>}{groups.length>0&&<div className="product-options">{groups.map(g=><label key={g.id}>{g.label}<select aria-label={`${g.label} de ${p.name}`} value={choices[g.id]||''} onChange={e=>setChoices({...choices,[g.id]:e.target.value})}><option value="">Elige {g.label.toLowerCase()}</option>{g.values.map(v=><option value={v.id} key={v.id}>{v.label}{(()=>{const adjustment=fulfillment==='shipping'?(v.shippingAdjustment??v.adjustment):v.adjustment;return adjustment?` (${adjustment>0?'+':''}${money(adjustment)})`:''})()}</option>)}</select></label>)}</div>}<div className="store-product-bottom"><strong>{!selected&&groups.length?'Desde ':''}{money(selected?.price??minPrice)}</strong>{quantity>0&&selected?<div className="quantity product-quantity"><Button variant="outline" size="icon" aria-label={`Reducir cantidad de ${p.name}`} onClick={()=>onChange(selected!.key,-1)}><Minus/></Button><span>{quantity}</span><Button variant="outline" size="icon" disabled={quantity>=Math.min(99,remaining)} aria-label={`Aumentar cantidad de ${p.name}`} onClick={()=>onAdd(p,choices)}><Plus/></Button></div>:<Button className="add-to-cart" disabled={!selected||remaining<=0} aria-label={`Agregar ${p.name} al carrito`} onClick={()=>onAdd(p,choices)}><Plus/>{remaining<=0?'Agotado':'Agregar'}</Button>}</div>{selected&&p.inventoryTracked? <p className="hint option-prompt">{remaining>0?`${remaining} disponibles`: "Agotado en esta sucursal"}</p>:null}{!selected&&groups.length>0&&<p className="hint option-prompt">Selecciona tus opciones para agregar.</p>}</div>;
 return <Dialog open={open} onOpenChange={setOpen}><article className="store-product"><div className="store-product-image">{p.bestSeller&&<span className="best-seller">MÁS VENDIDO</span>}<DialogTrigger asChild><button type="button" className="product-photo-trigger" aria-label={`Ver foto y detalles de ${p.name}`}><img src={imageUrl(p.image)} alt={p.name} loading="lazy"/><span className="product-photo-hint"><Expand size={16}/>Ver detalles</span></button></DialogTrigger></div>{details()}</article><DialogContent className="product-detail-dialog" showCloseButton={false}><Button type="button" variant="outline" size="icon" className="product-detail-close" aria-label="Cerrar detalles del producto" onClick={()=>setOpen(false)}><X/></Button><ProductImageViewer src={imageUrl(p.image)} name={p.name}/>{details(true)}</DialogContent></Dialog>
}
