'use client';
import {useEffect,useState,FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {Plus,Video,Trash2,X} from 'lucide-react';
import {api,CatalogVideo} from './shared';
import VideoCard from './catalog-video';
export default function VideoManager({shopId}:{shopId:string|null}){
 const [videos,setVideos]=useState<CatalogVideo[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[remove,setRemove]=useState<CatalogVideo|null>(null);
 async function load(){setLoading(true);setError('');try{setVideos((await api<{videos:CatalogVideo[]}>('/api/videos')).videos)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{if(shopId)void load()},[shopId]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setFormError('');try{if(!file)throw new Error('Selecciona un video.');if(file.size>90*1024*1024)throw new Error('El video debe pesar hasta 90 MB.');const d=await api<{video:CatalogVideo}>('/api/videos',{method:'POST',headers:{'Content-Type':file.type||'video/mp4','X-Video-Title':encodeURIComponent(title)},body:file});setVideos(v=>[d.video,...v]);setOpen(false)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function deleteVideo(){if(!remove)return;setBusy(true);setError('');try{await api('/api/videos',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:remove.id})});setVideos(v=>v.filter(x=>x.id!==remove.id));setRemove(null)}catch(e){setError((e as Error).message);setRemove(null)}finally{setBusy(false)}}
 return <section className="products-panel video-manager"><div className="section-title spread"><div><h2>Mis videos <span className="count">{videos.length}</span></h2><p>Muestra tus productos en movimiento.</p></div><Button disabled={!shopId} onClick={()=>{setTitle('');setFile(null);setFormError('');setOpen(true)}}><Plus/>Subir video</Button></div>{error&&<div className="error" role="alert">{error}<Button variant="link" onClick={load}>Volver a intentar</Button></div>}{loading?<p role="status">Cargando videos…</p>:videos.length?<div className="video-grid">{videos.map(v=><div className="managed-video" key={v.id}><VideoCard video={v}/><Button variant="ghost" aria-label={`Eliminar video ${v.title}`} onClick={()=>setRemove(v)}><Trash2/>Eliminar video</Button></div>)}</div>:<div className="video-empty"><Video size={28}/><h3>Agrega tu primer video</h3><p>{shopId?'Sube un MP4 o WebM de hasta 90 MB. Aparecerá en la sección Videos de tu tienda.':'Guarda tu negocio para subir videos a tu catálogo.'}</p></div>}
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="editor-dialog" showCloseButton={false}><div className="dialog-heading"><DialogTitle>Subir video</DialogTitle><Button aria-label="Cerrar" variant="ghost" disabled={busy} onClick={()=>setOpen(false)}><X/></Button></div><DialogDescription>El video se reproducirá dentro de tu tienda.</DialogDescription><form onSubmit={save}><fieldset disabled={busy}><label>Título del video<Input required maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Así se ve nuestra nueva colección"/></label><label className="upload-area"><Video size={34}/><span>{file?file.name:'Seleccionar video'}</span><small>MP4 o WebM · Hasta 90 MB · Sin comprimir</small><input aria-label="Archivo de video" type="file" required accept="video/mp4,video/webm" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>90*1024*1024){setFormError('Usa un video de hasta 90 MB.');e.target.value='';setFile(null)}else{setFile(f||null);setFormError('')}}}/></label></fieldset>{formError&&<p className="error" role="alert">{formError}</p>}<Button type="submit" className="full" disabled={busy}>{busy?'Subiendo video…':'Guardar video'}</Button></form></DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove(null)}}><AlertDialogContent><AlertDialogTitle>¿Eliminar este video?</AlertDialogTitle><AlertDialogDescription>“{remove?.title}” dejará de aparecer en tu tienda.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void deleteVideo()}}>Eliminar video</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>
}
