import {db,myShop,safe,sameOrigin,clean,HttpError} from '@/lib/store';
import {decodePromotion,type PromotionRule} from '@/app/promotion-rules';
export async function GET(){return safe(async()=>{const shop=await myShop();const rows=await db().prepare('SELECT id,code,percent,active,config FROM promotions WHERE shop_id=? ORDER BY code').bind(shop.id).all<{id:string,code:string,percent:number,active:number,config:string}>();return Response.json({promotions:rows.results.map(decodePromotion)},{headers:{'Cache-Control':'no-store'}})})}
export async function POST(req:Request){return safe(async()=>{sameOrigin(req);const shop=await myShop();const data=await req.json() as Record<string,unknown>;const code=clean(data.code,40).toUpperCase();if(!/^[A-Z0-9_-]{3,30}$/.test(code))throw new HttpError(400,'Usa un código de 3 a 30 letras o números.');const kind=data.kind||'percent',amount=Number(data.amount??data.percent),buy=Number(data.buy??3),pay=Number(data.pay??2),productIds=data.productIds??[],expiresAt=data.expiresAt??null,maxUses=data.maxUses??null;
 if(!['percent','fixed','bundle'].includes(String(kind))||!Number.isSafeInteger(amount)||amount<0||(kind==='percent'&&(amount<1||amount>100))||(kind==='fixed'&&(amount<1||amount>99999999))||!Number.isInteger(buy)||!Number.isInteger(pay)||buy<2||buy>99||pay<1||pay>=buy)throw new HttpError(400,'Revisa el descuento o las cantidades de la oferta.');
 if(!Array.isArray(productIds)||productIds.length>100||productIds.some(id=>typeof id!=='string'))throw new HttpError(400,'Selecciona productos válidos.');
 if(expiresAt!==null&&(typeof expiresAt!=='string'||!Number.isFinite(Date.parse(expiresAt))||Date.parse(expiresAt)<=Date.now()))throw new HttpError(400,'La fecha de vencimiento debe estar en el futuro.');
 if(maxUses!==null&&(!Number.isInteger(maxUses)||Number(maxUses)<1||Number(maxUses)>9999))throw new HttpError(400,'El límite debe ser de 1 a 9999 usos, o déjalo vacío.');
 if(productIds.length){const products=await db().prepare('SELECT id FROM products WHERE shop_id=?').bind(shop.id).all<{id:string}>();if(productIds.some(id=>!products.results.some(p=>p.id===id)))throw new HttpError(400,'Un producto seleccionado ya no existe en tu tienda.');}
 const rule:PromotionRule={kind:kind as PromotionRule['kind'],amount,buy,pay,productIds:[...new Set(productIds)],expiresAt:expiresAt?new Date(String(expiresAt)).toISOString():null,maxUses:maxUses as number|null};const config=JSON.stringify(rule),percent=kind==='percent'?amount:0;
 if(data.id){const row=await db().prepare('SELECT id FROM promotions WHERE id=? AND shop_id=?').bind(clean(data.id,60),shop.id).first();if(!row)throw new HttpError(404,'Promoción no encontrada.');const duplicate=await db().prepare('SELECT id FROM promotions WHERE shop_id=? AND code=? AND id<>?').bind(shop.id,code,data.id).first();if(duplicate)throw new HttpError(409,'Ese código ya existe.');await db().prepare('UPDATE promotions SET code=?,percent=?,config=? WHERE id=? AND shop_id=?').bind(code,percent,config,data.id,shop.id).run();}
 else{const exists=await db().prepare('SELECT id FROM promotions WHERE shop_id=? AND code=?').bind(shop.id,code).first();if(exists)throw new HttpError(409,'Ese código ya existe. Edítalo desde la lista.');await db().prepare('INSERT INTO promotions(id,shop_id,code,percent,config,active) VALUES(?,?,?,?,?,1)').bind(crypto.randomUUID(),shop.id,code,percent,config).run();}return Response.json({ok:true})})}
export async function PATCH(req:Request){return safe(async()=>{sameOrigin(req);const shop=await myShop();const data=await req.json() as {id?:unknown,active?:unknown};if(typeof data.active!=='boolean')throw new HttpError(400,'Estado no válido.');await db().prepare('UPDATE promotions SET active=? WHERE id=? AND shop_id=?').bind(data.active?1:0,clean(data.id,60),shop.id).run();return Response.json({ok:true})})}
