import {effectivePermissions,type AdminSection} from '@/app/admin-permissions';
import {passwordMode,currentAdmin} from './admin-auth';
import { demoShop,demoProducts,demoVideos } from '@/app/demo';
import type { Product,Shop,CatalogVideo } from '@/app/shared';
import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
export function db(){if(!env.DB)throw new Error('Database unavailable');return env.DB;}
export function bucket(){if(!env.BUCKET)throw new Error('Storage unavailable');return env.BUCKET;}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export async function owner(){const user=await getChatGPTUser();if(!user)throw new HttpError(401,'Inicia sesión para administrar tu catálogo.');return user.userId;}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');const target=new URL(req.url);const forwarded=req.headers.get('x-forwarded-host');const allowed=new Set((passwordMode()?[target.host]:[target.host,forwarded]).filter(Boolean));if(origin&&!allowed.has(new URL(origin).host))throw new HttpError(403,'Solicitud no permitida.');if(req.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'Solicitud no permitida.');}
export async function requireSection(section:AdminSection){if(passwordMode()){const user=await currentAdmin();if(!user)throw new HttpError(401,'Inicia sesión para continuar.');if(!effectivePermissions(user).includes(section))throw new HttpError(403,'Tu perfil no tiene acceso a esta sección.')}else await owner()}
export async function myShop(section?:AdminSection){if(section)await requireSection(section);const id=await owner();const shop=await db().prepare('SELECT id,name,phone FROM shops WHERE owner=?').bind(id).first();if(!shop)throw new HttpError(400,'Primero guarda los datos de tu negocio.');return shop;}
export async function safe(run:()=>Promise<Response>){try{return await run()}catch(e){if(e instanceof HttpError)return Response.json({error:e.message},{status:e.status});console.error('Store request failed',e);return Response.json({error:'No pudimos completar la solicitud. Tus cambios siguen en el formulario; inténtalo de nuevo.'},{status:503})}}
export function clean(value:unknown,max:number){if(typeof value!=='string')return '';return value.trim().slice(0,max)}
export async function publicStore(id:string){if(id==='ejemplo')return {shop:demoShop,products:demoProducts,videos:demoVideos};const shop=await db().prepare('SELECT id,name,phone,promotion_message AS promotionMessage FROM shops WHERE id=?').bind(id).first<Shop>();if(!shop)throw new HttpError(404,'No encontramos esta tienda.');const settings=await db().prepare('SELECT department_icons FROM shop_settings WHERE shop_id=?').bind(id).first<{department_icons:string}>();shop.departmentIcons=JSON.parse(settings?.department_icons||'{}');const products=await db().prepare('SELECT id,name,description,price,sale_price AS salePrice,shipping_price AS shippingPrice,image,options,inventory_tracked AS inventoryTracked,department,category,available_mty AS availableMty,available_cdmx AS availableCdmx FROM products WHERE shop_id=? ORDER BY created_at DESC').bind(id).all<Omit<Product,'options'>&{options:string}>();const videos=await db().prepare('SELECT id,title,source FROM videos WHERE shop_id=? ORDER BY created_at DESC').bind(id).all<CatalogVideo>();const stocks=await db().prepare('SELECT product_id AS productId,stock_key AS stockKey,branch,quantity FROM inventory WHERE shop_id=?').bind(id).all<{productId:string,stockKey:string,branch:'mty'|'cdmx',quantity:number}>();const byProduct:Record<string,Record<string,{mty:number,cdmx:number}>>={};for(const row of stocks.results){const data=byProduct[row.productId]??={};const item=data[row.stockKey]??={mty:0,cdmx:0};item[row.branch]=row.quantity}return {shop,products:products.results.map(p=>({...p,options:JSON.parse(p.options||'[]'),stock:byProduct[p.id]||{}})),videos:videos.results}}
