import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const shops=sqliteTable('shops',{id:text('id').primaryKey(),owner:text('owner').notNull().unique(),name:text('name').notNull(),phone:text('phone').notNull(),promotionMessage:text('promotion_message').notNull().default('')});
export const products=sqliteTable('products',{id:text('id').primaryKey(),shopId:text('shop_id').notNull().references(()=>shops.id),name:text('name').notNull(),description:text('description').notNull().default(''),price:integer('price').notNull(),shippingPrice:integer('shipping_price'),image:text('image').notNull(),options:text('options').notNull().default('[]'),inventoryTracked:integer('inventory_tracked').notNull().default(0),department:text('department').notNull().default('General'),category:text('category').notNull().default('General'),availableMty:integer('available_mty').notNull().default(1),availableCdmx:integer('available_cdmx').notNull().default(1),createdAt:integer('created_at').notNull()},t=>[index('products_shop_created_idx').on(t.shopId,t.createdAt)]);
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),token:text('token').notNull().unique(),requestKey:text('request_key').notNull().unique(),requestHash:text('request_hash').notNull(),shopId:text('shop_id').notNull(),createdAt:text('created_at').notNull(),snapshot:text('snapshot').notNull(),total:integer('total').notNull(),status:text('status').notNull().default('pending')},t=>[index('orders_shop_date_idx').on(t.shopId,t.createdAt)]);

export const videos=sqliteTable('videos',{id:text('id').primaryKey(),shopId:text('shop_id').notNull().references(()=>shops.id),title:text('title').notNull(),source:text('source').notNull(),createdAt:integer('created_at').notNull()},t=>[index('videos_shop_created_idx').on(t.shopId,t.createdAt)]);

export const promotions=sqliteTable('promotions',{id:text('id').primaryKey(),shopId:text('shop_id').notNull().references(()=>shops.id),code:text('code').notNull(),percent:integer('percent').notNull(),active:integer('active').notNull().default(1)},t=>[uniqueIndex('promotions_shop_code_idx').on(t.shopId,t.code)]);

export const productImports=sqliteTable('product_imports',{id:text('id').primaryKey(),shopId:text('shop_id').notNull().references(()=>shops.id),requestHash:text('request_hash').notNull(),createdAt:integer('created_at').notNull()});

export const pushSubscriptions=sqliteTable('push_subscriptions',{id:text('id').primaryKey(),shopId:text('shop_id').notNull(),endpoint:text('endpoint').notNull(),p256dh:text('p256dh').notNull(),auth:text('auth').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('push_shop_endpoint_idx').on(t.shopId,t.endpoint)]);
export const pushJobs=sqliteTable('push_jobs',{id:text('id').primaryKey(),shopId:text('shop_id').notNull(),title:text('title').notNull(),body:text('body').notNull(),targets:text('targets').notNull(),nextOffset:integer('next_offset').notNull().default(0),sent:integer('sent').notNull().default(0),failed:integer('failed').notNull().default(0),createdAt:integer('created_at').notNull()});

export const inventory=sqliteTable('inventory',{id:text('id').primaryKey(),shopId:text('shop_id').notNull(),productId:text('product_id').notNull(),stockKey:text('stock_key').notNull(),branch:text('branch').notNull(),quantity:integer('quantity').notNull().default(0)},t=>[uniqueIndex('inventory_variant_branch_idx').on(t.shopId,t.stockKey,t.branch)]);
export const inventoryEvents=sqliteTable('inventory_events',{id:text('id').primaryKey(),shopId:text('shop_id').notNull(),productId:text('product_id').notNull(),stockKey:text('stock_key').notNull(),branch:text('branch').notNull(),mode:text('mode').notNull(),quantity:integer('quantity').notNull(),expected:integer('expected'),productName:text('product_name').notNull(),options:text('options').notNull(),note:text('note').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('inventory_events_shop_date_idx').on(t.shopId,t.createdAt)]);
