import {db,myShop,publicStore,safe,sameOrigin,HttpError,clean} from '@/lib/store';
import {resolveSelection} from '@/app/product-options';
export async function GET(){return safe(async()=>{const shop=await myShop();const movements=await db().prepare('SELECT id,product_name AS productName,options,branch,mode,quantity,note,created_at AS date FROM inventory_events WHERE shop_id=? ORDER BY created_at DESC,id DESC LIMIT 50').bind(shop.id).all();return Response.json({movements:movements.results},{headers:{'Cache-Control':'no-store'}})})}
export async function POST(req:Request){return safe(async()=>{sameOrigin(req);const shop=await myShop(),data=await req.json() as {productId?:unknown,choices?:unknown,branch?:unknown,mode?:unknown,quantity?:unknown,expected?:unknown,note?:unknown,requestKey?:unknown};const mode=data.mode,branch=data.branch,quantity=Number(data.quantity),expected=Number(data.expected),key=clean(data.requestKey,60);if(!['set','add'].includes(String(mode))||!['mty','cdmx'].includes(String(branch))||!Number.isInteger(quantity)||quantity<0||quantity>1000000||(mode==='add'&&quantity<1)||!Number.isInteger(expected)||expected<0||!/^[-a-f0-9]{36}$/.test(key))throw new HttpError(400,'Revisa la sucursal y las unidades (números enteros).');const id=shop.id+':'+key;
 const previous=await db().prepare('SELECT product_id,stock_key,branch,mode,quantity FROM inventory_events WHERE id=? AND shop_id=?').bind(id,shop.id).first<{product_id:string,stock_key:string,branch:string,mode:string,quantity:number}>();const store=await publicStore(String(shop.id)),product=store.products.find(p=>p.id===data.productId);if(!product)throw new HttpError(404,'Producto no encontrado.');let selection;try{selection=resolveSelection(product,data.choices||{})}catch(e){throw new HttpError(400,(e as Error).message)}
 if(previous){if(previous.product_id!==product.id||previous.stock_key!==selection.key||previous.branch!==branch||previous.mode!==mode||previous.quantity!==quantity)throw new HttpError(409,'El movimiento cambió. Vuelve a intentarlo.');return Response.json({products:store.products})}
 try{await db().batch([
 db().prepare('INSERT INTO inventory(id,shop_id,product_id,stock_key,branch,quantity) VALUES(?,?,?,?,?,0) ON CONFLICT(shop_id,stock_key,branch) DO NOTHING').bind(crypto.randomUUID(),shop.id,product.id,selection.key,branch),
 db().prepare("UPDATE inventory SET quantity=CASE WHEN ?='add' THEN quantity+? WHEN quantity=? THEN ? ELSE -1 END WHERE shop_id=? AND stock_key=? AND branch=?").bind(mode,quantity,expected,quantity,shop.id,selection.key,branch),
 db().prepare('INSERT INTO inventory_events(id,shop_id,product_id,stock_key,branch,mode,quantity,expected,product_name,options,note,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,shop.id,product.id,selection.key,branch,mode,quantity,expected,product.name,JSON.stringify(selection.labels),clean(data.note,200),new Date().toISOString()),
 db().prepare('UPDATE products SET inventory_tracked=1 WHERE id=? AND shop_id=?').bind(product.id,shop.id)
 ])}catch(e){const saved=await db().prepare('SELECT product_id,stock_key,branch,mode,quantity FROM inventory_events WHERE id=? AND shop_id=?').bind(id,shop.id).first<{product_id:string,stock_key:string,branch:string,mode:string,quantity:number}>();if(saved&&saved.product_id===product.id&&saved.stock_key===selection.key&&saved.branch===branch&&saved.mode===mode&&saved.quantity===quantity)return Response.json({products:(await publicStore(String(shop.id))).products});if(String(e).includes('CHECK constraint failed'))throw new HttpError(409,'Las existencias cambiaron por otro movimiento o pedido. Actualiza la lista antes de corregirlas.');throw e}

 return Response.json({products:(await publicStore(String(shop.id))).products});})}
