'use client';
import { useEffect,useState,useRef,FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { ShoppingBag,Plus,Minus,ArrowLeft,ShoppingCart,Trash2,Check,Download,Printer,X,Send,Package } from 'lucide-react';
import { money,Product,Shop,api,imageUrl } from '@/app/shared';
import { usePageTools } from '@/app/webmcp';
export default function Storefront({shopId}:{shopId:string}){
 const [shop,setShop]=useState<Shop|null>(null),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Record<string,number>>({}),[ready,setReady]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[customer,setCustomer]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[notes,setNotes]=useState(''),[announcement,setAnnouncement]=useState('');
 async function load(){setLoading(true);setError('');try{const d=await api(`/api/store/${shopId}`);setShop(d.shop);setProducts(d.products);const next:Record<string,number>={};try{const stored=JSON.parse(localStorage.getItem(`cart:${shopId}`)||'{}');for(const p of d.products){const n=stored[p.id];if(Number.isInteger(n)&&n>0&&n<=99)next[p.id]=n}}catch{}setCart(next);setReady(true)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[shopId]);
 useEffect(()=>{if(ready)try{localStorage.setItem(`cart:${shopId}`,JSON.stringify(cart))}catch{}},[cart,ready,shopId]);
 const items=products.filter(p=>cart[p.id]>0),count=items.reduce((n,p)=>n+cart[p.id],0),total=items.reduce((n,p)=>n+p.price*cart[p.id],0);
 function change(id:string,delta:number){setCart(old=>({...old,[id]:Math.max(0,Math.min(99,(old[id]||0)+delta))}));if(delta>0)setAnnouncement(`${products.find(p=>p.id===id)?.name} agregado al carrito.`)}
 const requestRef=useRef({body:'',key:''});
 async function finish(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setFormError('');try{const payload={shopId,items:items.map(p=>({id:p.id,quantity:cart[p.id]})),customer,phone,address,notes};const body=JSON.stringify(payload);if(requestRef.current.body!==body)requestRef.current={body,key:crypto.randomUUID()};const d=await api<{token:string}>('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,requestKey:requestRef.current.key})});window.location.assign(`/pedido/${d.token}`)}catch(e){setFormError((e as Error).message);setBusy(false)}}
 usePageTools([{name:'add_products_to_cart',title:'Agregar productos al carrito',description:'Agrega productos visibles al carrito. No finaliza ni envía el pedido.',inputSchema:{type:'object',properties:{items:{type:'array',minItems:1,maxItems:100,items:{type:'object',properties:{id:{type:'string'},quantity:{type:'integer',minimum:1,maximum:99}},required:['id','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){const data=input as {items?:{id:string,quantity:number}[]};if(!data||!Array.isArray(data.items)||!data.items.length||data.items.length>100)throw new Error('Incluye los productos y cantidades.');const next={...cart};for(const item of data.items){if(!item||!products.some(p=>p.id===item.id)||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>99||(next[item.id]||0)+item.quantity>99)throw new Error('Producto o cantidad no válidos.');next[item.id]=(next[item.id]||0)+item.quantity}setCart(next);return {items:products.filter(p=>next[p.id]).map(p=>({id:p.id,name:p.name,quantity:next[p.id]}))}}}]);
 const cartContents=<>{!items.length?<Empty className="cart-empty"><EmptyHeader><ShoppingCart size={32}/><EmptyTitle>Tu carrito está esperando</EmptyTitle><EmptyDescription>Agrega los productos que quieras pedir.</EmptyDescription></EmptyHeader></Empty>:<div className="cart-items">{items.map(p=><div className="cart-item" key={p.id}><img src={imageUrl(p.image)} alt=""/><div><h3>{p.name}</h3><p>{money(p.price)}</p><div className="quantity"><Button variant="outline" size="icon" aria-label={`Quitar uno de ${p.name}`} onClick={()=>change(p.id,-1)}><Minus size={13}/></Button><span>{cart[p.id]}</span><Button variant="outline" size="icon" disabled={cart[p.id]>=99} aria-label={`Agregar uno de ${p.name}`} onClick={()=>change(p.id,1)}><Plus size={13}/></Button><Button variant="ghost" size="icon" aria-label={`Eliminar ${p.name} del carrito`} onClick={()=>setCart(c=>({...c,[p.id]:0}))}><Trash2 size={14}/></Button></div></div><strong>{money(p.price*cart[p.id])}</strong></div>)}</div>}<div className="cart-summary"><div className="total-line"><span>Total de productos</span><strong>{money(total)}</strong></div><p>MXN · Envío y disponibilidad por confirmar.</p><Button className="full" disabled={!count||busy} onClick={()=>{setCartOpen(false);setFormError('');setCheckout(true)}}>Finalizar pedido</Button><p className="payment-note">El pago se acuerda directamente con el negocio.</p></div></>;
 return <><header className="topbar"><div className="brand"><ShoppingBag/>{shop?.name||'Mi tienda'}</div><Button variant="outline" onClick={()=>setCartOpen(true)}><ShoppingCart/>Carrito <span className="cart-count">{count}</span></Button></header><main className="shop-workspace">{shopId==='ejemplo'&&<div className="demo-banner"><div><strong>Tienda de ejemplo</strong><span>Productos de muestra. Guarda el pedido y comparte su enlace por WhatsApp.</span></div><a href="/">Configurar mi catálogo →</a></div>}{loading?<p role="status">Cargando productos…</p>:error?<div className="error" role="alert">{error}<Button variant="link" onClick={load}>Volver a intentar</Button></div>:<div className="store-layout"><section><div className="store-intro"><p className="eyebrow">ELIGE TUS FAVORITOS</p><h1>¿Qué vas a pedir hoy?</h1><p>Elige tus productos y guarda tu pedido para compartirlo.</p><span className="pay-badge"><Check size={14}/>Pide aquí. Acuerda el pago después.</span></div><div className="section-title spread"><h2>Todos los productos <span className="count">{products.length}</span></h2></div>{products.length?<div className="store-products">{products.map(p=><article className="store-product" key={p.id}><div className="store-product-image"><img src={imageUrl(p.image)} alt={p.name} loading="lazy"/></div><div className="product-info"><h3>{p.name}</h3>{p.description&&<p className="product-description">{p.description}</p>}<div className="store-product-bottom"><strong>{money(p.price)}</strong>{cart[p.id]>0?<div className="quantity product-quantity"><Button variant="outline" size="icon" aria-label={`Reducir cantidad de ${p.name}`} onClick={()=>change(p.id,-1)}><Minus/></Button><span aria-label="Cantidad">{cart[p.id]}</span><Button variant="outline" size="icon" disabled={cart[p.id]>=99} aria-label={`Aumentar cantidad de ${p.name}`} onClick={()=>change(p.id,1)}><Plus/></Button></div>:<Button aria-label={`Agregar ${p.name} al carrito`} onClick={()=>change(p.id,1)}><Plus/>Agregar</Button>}</div></div></article>)}</div>:<Empty className="empty-catalog"><EmptyHeader><Package size={35}/><EmptyTitle>El catálogo se está preparando</EmptyTitle><EmptyDescription>Los productos aparecerán aquí en cuanto el negocio los agregue.</EmptyDescription></EmptyHeader></Empty>}</section><aside className="desktop-cart"><div className="cart-title"><h2>Tu pedido</h2><span>{count} artículos</span></div>{cartContents}</aside></div>}</main><div className="store-footer">{shop?.name} · Pedidos por WhatsApp · Precios en MXN</div><p className="sr-only" role="status">{announcement}</p>{count>0&&<Button className="mobile-cart-bar" onClick={()=>setCartOpen(true)}><span>Ver carrito · {count}</span><strong>{money(total)}</strong></Button>}
 <Dialog open={cartOpen} onOpenChange={setCartOpen}><DialogContent className="cart-dialog" showCloseButton={false}><div className="dialog-heading"><DialogTitle>Tu carrito</DialogTitle><Button variant="ghost" size="icon" aria-label="Cerrar carrito" onClick={()=>setCartOpen(false)}><X/></Button></div><DialogDescription>Revisa tus productos antes de finalizar.</DialogDescription>{cartContents}</DialogContent></Dialog>
 <Dialog open={checkout} onOpenChange={v=>{if(!busy)setCheckout(v)}}><DialogContent className="checkout-dialog" showCloseButton={false}><div className="dialog-heading"><DialogTitle>Finalizar pedido</DialogTitle><Button variant="ghost" size="icon" disabled={busy} aria-label="Cerrar" onClick={()=>setCheckout(false)}><X/></Button></div><DialogDescription>Guarda tu pedido. Todos los detalles quedarán en una página con su propio enlace.</DialogDescription><form onSubmit={finish}><fieldset disabled={busy}><label>Tu nombre<Input required value={customer} onChange={e=>setCustomer(e.target.value)} autoComplete="name" maxLength={80} placeholder="¿A nombre de quién?"/></label><label>Teléfono de contacto<Input required value={phone} onChange={e=>setPhone(e.target.value)} type="tel" autoComplete="tel" maxLength={25} pattern=".{10,25}" placeholder="Tu número de teléfono"/></label><label>Dirección de entrega<Textarea required value={address} onChange={e=>setAddress(e.target.value)} autoComplete="street-address" minLength={5} maxLength={400} placeholder="Calle, número, colonia, ciudad y referencias"/></label><label>Notas <span className="optional">(opcional)</span><Textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500} placeholder="Indicaciones o comentarios adicionales"/></label></fieldset><div className="total-line"><span>Total de productos</span><strong>{money(total)}</strong></div><p className="hint">El envío se confirma por separado. No se realiza ningún cobro en esta página.</p>{formError&&<div className="error" role="alert">{formError}</div>}<Button className="full" disabled={busy} type="submit">{busy?'Guardando tu pedido…':'Guardar pedido y ver resumen'}</Button></form></DialogContent></Dialog>
</>;
}
