'use client';
import {useEffect,useState,FormEvent} from 'react';
import PasswordField from '../password-field';
export default function Access(){
 const [mode,setMode]=useState('login'),[secret,setSecret]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const hash=new URLSearchParams(location.hash.slice(1));for(const kind of ['setup','invite']){const value=hash.get(kind);if(value){setMode(kind==='invite'?'accept':'setup');setSecret(value);history.replaceState(null,'',location.pathname);break}}},[]);
 async function submit(e:FormEvent){e.preventDefault();setError('');if(mode!=='login'&&password!==confirm){setError('Las contraseñas no coinciden.');return}setBusy(true);try{const res=await fetch(`/api/admin-auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,token:secret})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||'No pudimos iniciar sesión.');location.assign('/administrador')}catch(e){setError((e as Error).message);setBusy(false)}}
 return <main className="access-page"><section className="panel access-card"><p className="eyebrow">ADMINISTRACIÓN</p><h1>{mode==='login'?'Entra a tu tienda':'Crea tu acceso'}</h1><p>{mode==='login'?'Administra tus productos, fotos y pedidos.':'Elige tu correo y una contraseña privada de al menos 12 caracteres.'}</p><form onSubmit={submit}><label>Correo electrónico<input required type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254}/></label><PasswordField label="Contraseña" required autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/>{mode!=='login'&&<PasswordField label="Repite la contraseña" required autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} maxLength={128}/>}{error&&<p className="error" role="alert">{error}</p>}<button className="access-button" disabled={busy}>{busy?'Un momento…':mode==='login'?'Entrar':'Crear cuenta y entrar'}</button></form>{mode!=='login'&&<a href="/acceso">Ya tengo cuenta</a>}<a href="/">Ver catálogo</a></section></main>
}
