import {calculateDiscount,promotionLabel} from '@/app/promotion-rules';
import {resolveSelection,Choices} from '@/app/product-options';
import {findPromotion,promoCustomerHash} from '@/lib/promotions';
import { publicStore,safe,HttpError,clean,db,bucket,sameOrigin } from '@/lib/store';
import {isAvailable,stockFor,shippingFeeFor,promotionDiscount} from '@/app/shared';
import type {Fulfillment} from '@/app/shared';
import type {OrderSummary} from '@/app/order-types';
export async function POST(req:Request){return safe(async()=>{
 sameOrigin(req);
 const data=await req.json() as {items?:{id:string,quantity:number,choices?:Choices}[],shopId?:unknown,customer?:unknown,phone?:unknown,address?:unknown,notes?:unknown,requestKey?:unknown,fulfillment?:unknown,couponCode?:unknown};
 if(!data||!Array.isArray(data.items)||!data.items.length||data.items.length>100)throw new HttpError(400,'Agrega productos a tu carrito.');
 const customer=clean(data.customer,80),phone=clean(data.phone,25),address=clean(data.address,400),notes=clean(data.notes,500),shopId=clean(data.shopId,60),requestKey=clean(data.requestKey,60);
 if(!customer||!/^\+?[0-9 ()-]{10,25}$/.test(phone)||address.length<5)throw new HttpError(400,'Escribe tu nombre, teléfono y dirección completa.');
 if(!/^[a-f0-9-]{36}$/.test(requestKey))throw new HttpError(400,'Vuelve a intentar guardar el pedido.');
 if(!['mty','cdmx','shipping'].includes(String(data.fulfillment)))throw new HttpError(400,'Elige Monterrey, CDMX o paquetería antes de pedir.');const fulfillment=data.fulfillment as Fulfillment;
 const couponCode=clean(data.couponCode,40).toUpperCase();
 const payload=JSON.stringify({customer,phone,address,notes,shopId,fulfillment,couponCode,items:data.items});
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(payload))),b=>b.toString(16).padStart(2,'0')).join('');
 const previous=await db().prepare('SELECT token,request_hash FROM orders WHERE request_key=?').bind(requestKey).first<{token:string,request_hash:string}>();
 if(previous){if(previous.request_hash!==hash)throw new HttpError(409,'El pedido cambió. Vuelve a intentarlo.');return Response.json({token:previous.token},{headers:{'Cache-Control':'no-store'}})}
 const {shop,products}=await publicStore(shopId);const seen=new Set();
 const items=data.items.map(item=>{if(!item||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>99)throw new HttpError(400,'Revisa las cantidades de tu carrito.');const p=products.find(p=>p.id===item.id);if(!p||!isAvailable(p,fulfillment))throw new HttpError(409,'Un producto ya no está disponible en la sucursal elegida. Actualiza la tienda y revisa tu carrito.');let selected;try{selected=resolveSelection(p,item.choices||{},fulfillment)}catch(e){throw new HttpError(400,(e as Error).message)}if(seen.has(selected.key))throw new HttpError(400,'Combina las cantidades de las opciones repetidas.');seen.add(selected.key);if(stockFor(p,selected.key,fulfillment)<item.quantity)throw new HttpError(409,`No hay suficientes unidades de ${p.name} en la sucursal elegida.`);return {id:p.id,image:p.image,name:p.name,department:p.department,category:p.category,price:selected.price,quantity:item.quantity,options:selected.labels,choices:selected.choices,stockKey:selected.key}});
 // Preserve product photographs independently of later catalog edits.
 const receiptPhotos=new Map<string,string>();for(const item of items){const image=item.image;if(!image){item.image='/product-placeholder.svg';continue}if(image.startsWith('/samples/'))continue;if(receiptPhotos.has(image)){item.image=receiptPhotos.get(image)!;continue}const key=`receipt-images/${image}`;let saved=!!await bucket().head(key);if(!saved){const original=await bucket().get(image);if(original){await bucket().put(key,original.body,{httpMetadata:original.httpMetadata});saved=true}}item.image=saved?`/api/order-image/${image}`:'/product-placeholder.svg';receiptPhotos.set(image,item.image)}
 const subtotal=items.reduce((sum,i)=>sum+i.price*i.quantity,0),shippingFee=shippingFeeFor(fulfillment);
 const promotion=await findPromotion(shopId,couponCode),discount=promotion?calculateDiscount(items,promotion):0;
 if(promotion&&discount===0)throw new HttpError(400,'Tu carrito no cumple las condiciones de esta promoción. Revisa los productos y las cantidades.');
 const customerHash=promotion?await promoCustomerHash(phone):'';
 const order:OrderSummary={id:crypto.randomUUID(),token:crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),date:new Date().toISOString(),shop,items,customer,phone,address,notes,subtotal,shippingFee,discount,couponCode:promotion?.code,discountPercent:promotion?.kind==='percent'?promotion.amount:undefined,promotionDescription:promotion?promotionLabel(promotion):undefined,total:subtotal-discount+shippingFee,status:'pending',fulfillment};
 try{const statements=[];if(promotion&&promotion.id!=='demo')statements.push(db().prepare('INSERT INTO promotion_uses(request_key,promotion_id,customer_hash,config,created_at) SELECT ?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM orders WHERE request_key=?) ON CONFLICT(request_key) DO NOTHING').bind(requestKey,promotion.id,customerHash,promotion.config!,order.date,requestKey));const branch=fulfillment==='cdmx'?'cdmx':'mty';for(const item of items){
 statements.push(db().prepare('INSERT INTO inventory(id,shop_id,product_id,stock_key,branch,quantity) SELECT ?,?,?,?,?,0 WHERE EXISTS(SELECT 1 FROM products WHERE id=? AND shop_id=? AND inventory_tracked=1) ON CONFLICT(shop_id,stock_key,branch) DO NOTHING').bind(crypto.randomUUID(),shop.id,item.id,item.stockKey,branch,item.id,shop.id));
 statements.push(db().prepare('UPDATE inventory SET quantity=quantity-? WHERE shop_id=? AND stock_key=? AND branch=? AND EXISTS(SELECT 1 FROM products WHERE id=? AND shop_id=? AND inventory_tracked=1) AND NOT EXISTS(SELECT 1 FROM orders WHERE request_key=?)').bind(item.quantity,shop.id,item.stockKey,branch,item.id,shop.id,requestKey));
 statements.push(db().prepare('INSERT INTO inventory_events(id,shop_id,product_id,stock_key,branch,mode,quantity,product_name,options,note,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM products WHERE id=? AND shop_id=? AND inventory_tracked=1) AND NOT EXISTS(SELECT 1 FROM orders WHERE request_key=?)').bind(order.id+':'+statements.length,shop.id,item.id,item.stockKey,branch,'order',-item.quantity,item.name,JSON.stringify(item.options),'Pedido '+order.id.slice(0,8),order.date,item.id,shop.id,requestKey));
 }statements.push(db().prepare('INSERT INTO orders (id,token,request_key,request_hash,shop_id,created_at,snapshot,total,status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(request_key) DO NOTHING').bind(order.id,order.token,requestKey,hash,shop.id,order.date,JSON.stringify(order),order.total,'pending'));await db().batch(statements);} catch(e){const previous=await db().prepare('SELECT token,request_hash FROM orders WHERE request_key=?').bind(requestKey).first<{token:string,request_hash:string}>();if(previous&&previous.request_hash===hash)return Response.json({token:previous.token});if(String(e).includes('promotion_limit'))throw new HttpError(409,'Este teléfono ya usó la promoción el máximo de veces permitido. Quita el código para continuar.');if(String(e).includes('promotion_unavailable'))throw new HttpError(409,'La promoción cambió, venció o fue desactivada. Vuelve a aplicar el código.');if((String(e).includes('inventory_unavailable')||String(e).includes('CHECK constraint failed')))throw new HttpError(409,'El inventario cambió. Actualiza el catálogo y revisa las cantidades antes de guardar.');throw e}
 const saved=await db().prepare('SELECT token,request_hash FROM orders WHERE request_key=?').bind(requestKey).first<{token:string,request_hash:string}>();if(!saved)throw new Error('Order not saved');if(saved.request_hash!==hash)throw new HttpError(409,'El pedido cambió. Vuelve a intentarlo.');
 return Response.json({token:saved.token},{status:201,headers:{'Cache-Control':'no-store'}});
})}
